feat: support Vietnamese language
medusajs/medusa pull request #10244
Opened 2024-11-24 14:29 UTC by ralphilius

2024-11-25 12:47 UTC, kasperkristensen approved these changes

2024-11-26 08:50 UTC, kasperkristensen requested changes
Hi @ralphilius, can I get you to fix the merge conflicts, also there was some new keys added that needs to be included before we can merge the PR:

Validation failed for vi.json:
  Missing required key: "title" at products.create
  Missing required key: "description" at products.create
  Missing required key: "successToast" at products.media

2024-11-28 05:48 UTC, chrislaai commented on packages/admin/dashboard/src/i18n/translations/index.ts
> +import vi from "./tr.json"
Should it be'./vi.json'?

2024-11-28 08:43 UTC, ralphilius commented on packages/admin/dashboard/src/i18n/translations/index.ts
> +import vi from "./tr.json"
Yes. I've updated in the latest push.

2024-12-01 02:52 UTC, ralphilius commented
@kasperkristensen I've made all the changes needed. Please help review. Thanks

2025-01-17 01:56 UTC, closed without merging