docs: Update Redis connection string instructions for Railway
medusajs/medusa pull request #10246
Opened 2024-11-24 22:35 UTC by qbitdoge

### What
Updated the Railway Redis and Postgres connection string instructions:
- Changed `DATABASE_URL` to use `${{Postgres.RAILWAY_PRIVATE_DOMAIN}}`
- Updated `REDIS_URL` to use `?family=0` to support both IPv6 and IPv4 connections.
- Adjusted instructions to reflect the new `REDIS_URL` configuration

### Why
Railway [does not support IPv4 private networking](https://docs.railway.com/reference/private-networking#caveats), so users need clearer guidance to enable IPv6. Additionally, the egress fee note ensures users are aware of [potential costs](https://docs.railway.com/reference/pricing/plans#resource-usage-pricing) when using public endpoints.

### How
Edited the relevant section in the documentation for clarity and conciseness.

### Testing
Changes are text-only and have been reviewed for accuracy.

2024-11-25 08:05 UTC, shahednasser requested changes
Thank you for your contribution!

Referring to [this documentation](https://docs.railway.com/guides/private-networking#known-configuration-requirements-for-ipv6), it says setting `family=0` supports both IPv6 and IPv4 connections, so I think we should set it to that. Then we don't need to add the note about `Redis.REDIS_PUBLIC_URL`

Another thing: the `REDIS_URL` is set in two places (for worker and server environments). Can you update it there?

Also, it would be great if you can update `DATABASE_URL` as well to be `${{Postgres.RAILWAY_PRIVATE_DOMAIN}}` as this Railway change (regarding fees) seem to apply to it as well.

2024-11-26 01:03 UTC, qbitdoge commented
@shahednasser thanks so much for the feedback and suggestions. 
I’ve addressed all the changes as requested.
Let me know if there’s anything else that needs adjustment.

2024-11-26 07:50 UTC, shahednasser requested changes

2024-11-26 07:50 UTC, shahednasser commented on www/apps/resources/app/deployment/medusa-application/railway/page.mdx
> +- `REDIS_URL`'s value is automatically generated using Railway’s template syntax. Please note that Railway does not support IPv4 private networking, so make sure to add the `?family=0` to the connect
```suggestion
- `REDIS_URL`'s value is automatically generated using Railway’s template syntax. You add the `?family=0` to the connection string to support both IPv6 and IPv4 connections.
```

2024-11-26 07:50 UTC, shahednasser commented on www/apps/resources/app/deployment/medusa-application/railway/page.mdx
> +- `REDIS_URL`'s value is automatically generated using Railway’s template syntax. Please note that Railway does not support IPv4 private networking, so make sure to add the `?family=0` to the connect
Also can you add the same line in the section below for worker mode environment variables?

2024-11-26 14:51 UTC, qbitdoge commented
@shahednasser done! anything else?

2024-11-26 15:27 UTC, shahednasser approved these changes
LGTM thanks!

2024-11-26 16:43 UTC, merged

2024-11-27 10:42 UTC, waptik commented
Putting this here as there was some error with postgres. 
`DATABASE_URL` value should be changed to `${{Postgres.DATABASE_URL}}` instead of `${{Postgres.RAILWAY_PRIVATE_DOMAIN}}` because its value remains `postgres.railway.internal` instead of `postgresql://postgres:xxxxxx@postgres.railway.internal:5432/railway`
Another PR must be created to fix it

2024-11-27 11:09 UTC, shahednasser commented
You're correct @waptik , when I used it in Railway's dashboard it showed me that the value was the full address but it wasn't. I'll open another PR to make the update

2024-11-28 05:39 UTC, waptik commented
> You're correct @waptik , when I used it in Railway's dashboard it showed me that the value was the full address but it wasn't. I'll open another PR to make the update

Can you turn your working architecture into template because i followed the guide and my server instance has been crashing because of `index.html`
<img width="983" alt="image" src="https://github.com/user-attachments/assets/fb5ed72f-bd64-4cda-a6bb-1a89456ea990">

My variables
```
ADMIN_CORS="https://${{RAILWAY_PUBLIC_DOMAIN}},https://${{RAILWAY_PRIVATE_DOMAIN}}"
AUTH_CORS="https://${{RAILWAY_PUBLIC_DOMAIN}},https://${{RAILWAY_PRIVATE_DOMAIN}}"
STORE_CORS="http://localhost:8000,https://docs.medusajs.com"
DATABASE_URL="${{Postgres.DATABASE_URL}}"
REDIS_URL="${{Redis.REDIS_URL}}?family=0"
JWT_SECRET="****************"
COOKIE_SECRET="****************"
PAYSTACK_API_KEY="****************"
NODE_ENV="production"
PORT="9000"
MEDUSA_ADMIN_EMAIL="me@email.xyz"
MEDUSA_ADMIN_PASSWORD="****************"
MEDUSA_ADMIN_ONBOARDING_TYPE="default"
RAILWAY_PUBLIC_DOMAIN_VALUE="https://${{RAILWAY_PUBLIC_DOMAIN}}"
DISABLE_MEDUSA_ADMIN="false"
MEDUSA_WORKER_MODE="server"
```

2024-11-28 07:43 UTC, shahednasser commented
Thank you for your feedback, I would double check that you've followed every step, and if the error is still happening you can open an issue describing your error