Twilio SMS plugin
medusajs/medusa pull request #103
Opened 2020-09-08 09:30 UTC by olivermrbl

2020-09-08 10:01 UTC, srindom requested changes

2020-09-08 10:01 UTC, srindom commented on packages/medusa-plugin-twilio-sms/src/services/twilio-sms.js
> +}
Maybe make this as generic as possible. I.e.:
```js
  async sendSms(config) {
    const toSend = {
        from: this.options_.from_number,
        ...config
    }
    return this.twilioClient.messages.create(toSend)
  }
```
This way we default to the `from_number` in `options` but we give the flexibility to do other things with the plugin if needed

2020-09-09 08:48 UTC, olivermrbl commented
Is this good to go? @srindom

2020-09-09 08:50 UTC, srindom approved these changes
love it 🐑

2020-09-09 08:52 UTC, merged