Changed default request payload to null
medusajs/medusa pull request #1044
Opened 2022-02-11 13:00 UTC by nielswart

## What

changed the default request payload to `null`

## Why

Get requests have an empty body and this results in 403 errors see #1043

## How

set default parameter value to `null` and changed type to union of `object` and `null`, i.e `object | null`

## Test

I don't know how to test this?

2022-02-11 13:11 UTC, adrien2p commented
We should privilege Record<string, unknown> over object type.

Don’t use object as a type. The object type is currently hard to use ([see this issue](https://github.com/microsoft/TypeScript/issues/21732)).
Consider using Record<string, unknown> instead, as it allows you to more easily inspect and use the keys.

2022-02-14 13:16 UTC, olivermrbl commented
> We should privilege Record<string, unknown> over object type.
> 
> Don’t use object as a type. The object type is currently hard to use ([see this issue](https://github.com/microsoft/TypeScript/issues/21732)). Consider using Record<string, unknown> instead, as it allows you to more easily inspect and use the keys.
> 
> at the moment, the object type is widely used in the project. I think it is something to discuss but if anybody has a counter argument, in those cases Record is better

I like this idea. As far as I can see nothing really speaks for using `object` over `Record<K, V>` right? Record is actually quite nice because it allows us to access object properties without TypeScript complaining.

2022-02-15 09:37 UTC, srindom submitted a review, later dismissed

2022-02-15 09:38 UTC, srindom requested changes

2022-02-15 09:38 UTC, srindom commented on packages/medusa-js/src/request.ts
> +    payload: object | null = null,
As per @adrien2p's suggestion lets do this:

```suggestion
    payload: Record<string, unknown> | null = null,
```

2022-02-15 09:42 UTC, srindom commented
Have tested that the fix works so we just need that small fix and then we can merge

2022-02-15 09:44 UTC, srindom approved these changes

2022-02-15 11:57 UTC, adrien2p commented
Yes it is in my branch already

2022-02-17 15:59 UTC, srindom commented
@adrien2p @nielswart building `@medusajs/medusa-js` still seems to cause trouble with this update - any ideas? 

Maybe: `Record<symbol, unknown>` is more appropriate?

2022-02-18 08:30 UTC, nielswart commented
@srindom @adrien2p how can I help to get this PR completed?

2022-02-18 08:31 UTC, adrien2p commented
Hey 👋 did you look at the review comment I suggested ?

2022-02-18 08:35 UTC, adrien2p commented
Normally you should see just above something with "has pending changes" no?

2022-02-18 08:38 UTC, nielswart commented
> Normally you should see just above something with "has pending changes" no?

Sorry, but I don't see anything on the review?

2022-02-23 16:15 UTC, olivermrbl commented
@adrien2p The current suggestion of using `Record<string, unknown>` results in the following error at build time:
`Index signature for type 'string' is missing in type`

Do you happen to know any ways of solving for this?

As far as I can see, the issue is rooted in our types having fixed properties, which does not play nice with Typescript's `Record<string, unknown>` since this indicates that we can have any string as keys in our payloads (which is not really the case either, so using records might be misleading???).

2022-02-23 16:17 UTC, olivermrbl commented
Where is this suggestion @adrien2p ? I am also having a hard time finding it 😅

2022-02-23 16:17 UTC, adrien2p commented
Line 186 actually

2022-02-23 16:19 UTC, olivermrbl commented
Can you throw your suggestion as a comment here? I can't see it :'(

2022-02-23 16:24 UTC, adrien2p commented on packages/medusa-js/src/request.ts
> +    payload: Record<string, unknown> | null = null,
@olivermrbl @nielswart Rho my bad, did not submit the review 😂

2022-02-24 05:28 UTC, nielswart commented on packages/medusa-js/src/request.ts
> +    payload: Record<string, unknown> | null = null,
Thanks @olivermrbl and @adrien2p !

2022-02-24 09:26 UTC, olivermrbl approved these changes
LGTM!

2022-02-24 11:37 UTC, merged