chore: add Arabic translation
medusajs/medusa pull request #10463
Opened 2024-12-06 02:44 UTC by zaaakher

This PR adds Arabic localization. 

Ideally, we might need to add `dir="rtl"` conditionally somewhere to flip the UI to make it RTL

2024-12-07 11:12 UTC, MEClouds commented on packages/admin/dashboard/src/i18n/languages.ts
> +    ltr: true,
change LTR to false (because Arabic use RTL)

2024-12-07 11:44 UTC, MEClouds requested changes

2024-12-07 11:44 UTC, MEClouds commented on packages/admin/dashboard/src/i18n/languages.ts
> +    date_locale: arSA,
use ar for generic Arabic,
date_locale: ar ,

2024-12-07 11:44 UTC, MEClouds commented on packages/admin/dashboard/src/i18n/languages.ts
> +    display_name: "عربي",
display_name: "العربية",

2024-12-08 02:13 UTC, zaaakher commented
@MEClouds Done 👍

2025-01-04 12:11 UTC, alsherif-khalaf commented
What is missing here ?

2025-01-11 01:53 UTC, wasims1 approved these changes

2025-01-11 02:01 UTC, wasims1 commented
hi could you please merge this pull it's only adding a translation @sgirones  @mrnbpt 

thanks!

2025-01-12 23:36 UTC, TheMikeyRoss commented
Any updates on this one? so that it can be included in the next release

2025-01-14 14:02 UTC, RoxDevvv commented
i need that

2025-01-27 10:04 UTC, TheMikeyRoss commented
I just want to point out:

Arabic: ~420 million speakers globally.
Macedonian: ~2-3 million speakers globally.

2025-01-27 11:58 UTC, sradevski commented
@zaaakher can you please rebase and add all missing keys? We'll get it merged but it currently has merge conflicts.

2025-01-27 13:03 UTC, zaaakher commented
I tried to rebase but i think i did something wrong

2025-01-27 13:06 UTC, zaaakher commented
@sradevski I think i screwed up this PR, so I made a new one https://github.com/medusajs/medusa/pull/11174

2025-01-27 13:06 UTC, closed without merging

2025-01-27 16:07 UTC, TheMikeyRoss commented
@zaaakher We've all been there 😄. Thanks anyway