Added Cloudflare R2 guide for Object Storage
medusajs/medusa pull request #10497
Opened 2024-12-08 16:10 UTC by ehtisham-afzal

2024-12-13 20:37 UTC, ogcatt commented
I receive this error when following your guide: Credential access key has length 40, should be 32

2024-12-28 16:05 UTC, ehtisham-afzal commented
> I receive this error when following your guide: `Credential access key has length 40, should be 32`

can you share the example of your credentials you're using

2024-12-31 09:01 UTC, shahednasser requested changes
Thank you for your contribution!

2024-12-31 09:01 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +    1. Create a [Cloudflare free account](https://supabase.com/dashboard/sign-in) if you don’t have.
```suggestion
    1. Create a [Cloudflare account](https://dash.cloudflare.com/sign-up).
```

2024-12-31 09:01 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +       - Navigate to R2 Object Storage in your dashboard
```suggestion
       - Navigate to R2 Object Storage in your dashboard. You may need to provide your credit-card information.
```

2024-12-31 09:01 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +       - Open your bucket's Settings
```suggestion
       - On your bucket's dashboard, click on the Settings tab.
```

2024-12-31 09:01 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +       - Enable R2.dev subdomain access
```suggestion
       - Scroll down to the Public Access section, and click on "Allow Access" in the "R2.dev subdomain" card.
```

2024-12-31 09:01 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +       - Find your Account ID in the R2 dashboard's top right corner
Would remove this point and instead add it to the [options table](https://docs.medusajs.com/resources/architectural-modules/file/s3#s3-file-module-options) similar to other platforms. Add for `endpoint` the explanation on how to set it for Cloudflare

2024-12-31 09:01 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +    4. Set up your credentials:
```suggestion
    4. Retrieve credentials:
```

2024-12-31 09:01 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +       - [Generate API tokens](https://dash.cloudflare.com/?to=/:account/r2/api-tokens):
```suggestion
       - [Go to API tokens page](https://dash.cloudflare.com/?to=/:account/r2/api-tokens):
```

2024-12-31 09:01 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +         - Under **Permissions**, select appropriate permission types
Can you specify here the appropriate permission type? I think it should be "Object Read & Write"

Also, remove the bold on "Permissions"

2024-12-31 09:01 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +         - Optionally scope token to specific buckets for Object Read/Write permissions
```suggestion
         - You can optionally specify the buckets that this API token has access to under the "Specify bucket(s)" section.
```

2024-12-31 09:01 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +         - Click **Create API Token**
```suggestion
         - Once done, click the "Create API Token" button.
```

2024-12-31 09:01 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +         - Edit the **R2 Token** name
```suggestion
         - Edit the "R2 Token" name
```

2024-12-31 09:01 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +         - Select **Create API token**
```suggestion
         - Select "Create API token"
```

2024-12-31 09:01 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +         - Save the generated token as your **`S3_ACCESS_KEY_ID`, `S3_SECRET_ACCESS_KEY`**
Actually you get an access key ID and secret access key after creating the token. Let's instruct the user to use that instead.

```suggestion
         - You'll receive an access key ID and a secret access key. Save them to use them later for the `S3_ACCESS_KEY_ID` and `S3_SECRET_ACCESS_KEY` environment variables.
```

2024-12-31 09:01 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +       ```
Remove

2024-12-31 09:01 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +       - Find your Account ID in the R2 dashboard's top right corner
I just realized you added it to the table, so just include the instructions of where you can find the account ID in there.

2025-01-02 07:32 UTC, shahednasser requested changes
I see you marked some comments as resolved when you didn't address them. I unresolved them, can you fix them?

2025-01-03 16:30 UTC, ehtisham-afzal commented
> I see you marked some comments as resolved when you didn't address them. I unresolved them, can you fix them?

I reviewed the changes and its correct and updated with your suggestions 

![image](https://github.com/user-attachments/assets/4e2a8d60-9490-449a-a60c-06600641664a)

2025-01-06 07:05 UTC, shahednasser requested changes
There are three comments that you seem to be missing so I'll add the link to them:

- https://github.com/medusajs/medusa/pull/10497/files#r1899991666
- https://github.com/medusajs/medusa/pull/10497/files#r1899993515
- https://github.com/medusajs/medusa/pull/10497/files#r1899995677

If it's still unclear, please let me know

2025-01-08 07:43 UTC, shahednasser approved these changes
Thanks!

2025-01-08 08:06 UTC, merged