docs: how to add new admin route under existing route
medusajs/medusa pull request #10652
Opened 2024-12-18 08:52 UTC by eugenepro2

This PR updated docs and describe how to add new admin route under existing route.
Ref: https://github.com/medusajs/medusa/pull/10587#issuecomment-2550697254

2024-12-18 18:14 UTC, shahednasser requested changes
Thank you for opening this PR! Just need a few changes

2024-12-18 18:14 UTC, shahednasser commented on www/apps/book/app/learn/fundamentals/admin/ui-routes/page.mdx
> +### Route Under Existing Admin Route
```suggestion
### Route Under Existing Admin Route

```

2024-12-18 18:14 UTC, shahednasser commented on www/apps/book/app/learn/fundamentals/admin/ui-routes/page.mdx
> +You can locate a route under an existing route. For example, you can locate a route under the orders route in the sidebar.
```suggestion
You can add a custom UI route under an existing route. For example, you can add a route under the orders route:
```

2024-12-18 18:14 UTC, shahednasser commented on www/apps/book/app/learn/fundamentals/admin/ui-routes/page.mdx
> +```
~~~suggestion
```

The `nested` property passed to `defineRouteConfig` specifies which route this custom route is nested under. This route will now show in the sidebar under the existing "Orders" sidebar item.
~~~

2024-12-19 07:48 UTC, eugenepro2 commented
@shahednasser Thanks for your suggestions. I've committed this changes. Please have a look.

2024-12-19 07:52 UTC, shahednasser requested changes

2024-12-19 07:52 UTC, shahednasser commented on www/apps/book/app/learn/fundamentals/admin/ui-routes/page.mdx
> +The `nested` property passed to `defineRouteConfig` specifies which route this custom route is nested under. This route will now show in the sidebar under the existing "Orders" sidebar item.
```suggestion
The `nested` property passed to `defineRouteConfig` specifies which route this custom route is nested under. This route will now show in the sidebar under the existing "Orders" sidebar item.

```

Need to add a new line after the sentence / before the divider

2024-12-19 07:52 UTC, shahednasser commented on www/apps/book/app/learn/fundamentals/admin/ui-routes/page.mdx
> +### Route Under Existing Admin Route
@eugenepro2 there's also this change please (need to add a new line after the header)

2024-12-19 08:08 UTC, shahednasser approved these changes
LGTM thanks! Will merge this once the next release is out.

2025-01-20 12:55 UTC, eugenepro2 commented
@shahednasser can you merge it?

2025-01-20 13:21 UTC, merged