Fix: Add exception formatter util
medusajs/medusa pull request #1079
Opened 2022-02-17 15:11 UTC by pKorsholm

**What** 
- add `utils/exception-formatter.ts` for handling specific exceptions like duplicate keys in the database
- make the general errorhandler more strict in that it doesn't return any errors it doesn't know, instead it returns 'unknown_error'

2022-02-21 17:19 UTC, srindom requested changes

2022-02-23 08:49 UTC, pKorsholm commented on integration-tests/api/__tests__/admin/discount.js
> +          "Key (code)=(TESTING) already exists."
Changed it up for something like this: "Discount with code TESTING already exists.", db tables with an underscore in the name gets represented like this: "Product_collection with handle test-collection already exists".

We could remove the underscore as well if we want? thoughts @srindom?

2022-02-23 09:31 UTC, pKorsholm commented on integration-tests/api/__tests__/admin/discount.js
> +          "Key (code)=(TESTING) already exists."
Also changed up the foreign key error from "Key (customer_id)=(test-customer-27) is not present in table "customer"." to "Customer with customer_id test-customer-27 does not exist"

2022-02-23 16:56 UTC, pKorsholm commented on integration-tests/api/__tests__/admin/discount.js
> +          "Key (code)=(TESTING) already exists."
just fixed the underscore as discussed earlier @srindom

2022-03-14 08:30 UTC, closed without merging