Feat: Delete customer group
medusajs/medusa pull request #1102
Opened 2022-02-22 17:02 UTC by pKorsholm

**What**
- delete functionality for customer groups

**Testing** 
- Add integration tests: 
  - `removes customer group from get endpoint`, tests that `GET /admin/customer-groups/{id}` returns 404 after deletion
  - `removes customer group from customer upon deletion` tests that the group is removed from the customer after deletion

2022-02-23 11:36 UTC, olivermrbl requested changes
Great work! Couple of comments 👍

2022-02-23 11:36 UTC, olivermrbl commented on packages/medusa/src/api/routes/admin/customer-groups/delete-customer-group.ts
> + *               $ref: "#/components/schemas/customergroup"
```suggestion
 *       application/json:
 *         schema:
 *           properties:
 *             id:
 *               type: string
 *               description: The id of the deleted customer group.
 *             object:
 *               type: string
 *               description: The type of the object that was deleted.
 *             deleted:
 *               type: boolean
```

2022-02-23 11:36 UTC, olivermrbl commented on packages/medusa/src/api/routes/admin/customer-groups/index.ts
Would be great to add `export type AdminCustomerGroupsDeleteRes = DeleteResponse` for when we add the endpoints in `medusa-js` 👍

2022-02-24 12:58 UTC, srindom approved these changes
Great work!

2022-02-24 13:11 UTC, olivermrbl approved these changes

2022-02-24 13:20 UTC, merged