feat(medusa): Improve config loading
medusajs/medusa pull request #1290
Opened 2022-03-31 21:54 UTC by adrien2p

2022-04-03 19:10 UTC, srindom reviewed
Would it make sense to move everything related to config to be configurable by `medusa-config.js` and then have `loaders/config` pull in values from there with defaults in case values are not provided. This way we remove `process.env` usage in the core and move it to the project level. 

We will also eliminate everything opinionated about what your .env files should be called as you would now use:

```js
// medusa-config.js

dotenv.config([whatever your file is])

exports.module = {
 ... usage of your .env how ever you want 
}
```

2022-04-03 19:17 UTC, adrien2p commented
> Would it make sense to move everything related to config to be configurable by `medusa-config.js` and then have `loaders/config` pull in values from there with defaults in case values are not provided. This way we remove `process.env` usage in the core and move it to the project level.
> 
> We will also eliminate everything opinionated about what your .env files should be called as you would now use:
> 
> ```js
> // medusa-config.js
> 
> dotenv.config([whatever your file is])
> 
> exports.module = {
>  ... usage of your .env how ever you want 
> }
> ```

I am agree, should we remove the dotenv package from the core then?

2022-04-04 15:37 UTC, adrien2p commented
@srindom is that alright even if it breaks the existing ? 

At the moment the users does not load there envs themselves

2022-04-05 13:13 UTC, adrien2p commented
@srindom I am waiting to re run the tests because locally they are green 
<img width="1792" alt="Screenshot 2022-04-05 at 15 13 27" src="https://user-images.githubusercontent.com/25098370/161761771-9fdaf38b-4b10-4760-b8b8-b6c4d556afed.png">

2022-04-08 22:52 UTC, adrien2p commented
Fixes #827

2022-04-14 10:02 UTC, srindom requested changes

2022-04-14 10:02 UTC, srindom commented on packages/medusa/src/services/invite.ts
> +    console.log("-------", JSON.stringify(this.configModule_, null, 4))
issue: rm

2022-04-14 10:02 UTC, srindom commented on packages/medusa/src/services/invite.ts
> +    console.log("----", this.configModule_)
issue: rm

2022-04-14 10:02 UTC, srindom commented on packages/medusa/src/types/global.ts
> +    cookieSecret?: string
todo: snake_case

2022-04-14 10:02 UTC, srindom commented on packages/medusa/src/types/global.ts
> +  }[]
```suggestion
  plugins: ({
    resolve: string
    options: Record<string, unknown>
  } | string)[]
```

2022-04-14 10:44 UTC, adrien2p commented on packages/medusa/src/loaders/config.ts
> +
do you mean something like that?

```
return {
    projectConfig: {
      jwt_secret:
        process.env.JWT_SECRET ?? process.env.COOKIE_SECRET ?? "supersecret",
      cookie_secret:
        process.env.JWT_SECRET ?? process.env.COOKIE_SECRET ?? "supersecret",
      ...configModule?.projectConfig,
    },
    plugins: configModule?.plugins ?? [],
  }
}
```

2022-04-14 10:46 UTC, adrien2p commented on packages/medusa/src/loaders/config.ts
> +  if (!configModule?.projectConfig?.jwtSecret) {
should not happen with the remarks above if I set it directly from the loader

2022-04-14 12:38 UTC, adrien2p commented
@srindom this branch is up to date with develop but still fail with the same tests as some other PR

2022-04-17 12:18 UTC, srindom reviewed
LGTM - will let Oli approve too :)
cc: @olivermrbl

2022-04-20 08:07 UTC, srindom approved these changes

2022-04-20 08:10 UTC, olivermrbl approved these changes
🙌

2022-04-21 06:29 UTC, olivermrbl commented
Ready to merge this one @adrien2p ?

2022-04-21 08:44 UTC, adrien2p commented
Yes 🙌🚀 when you want

2022-04-21 10:46 UTC, olivermrbl commented
Confirming with @srindom?

2022-04-21 10:49 UTC, merged