Feature/swaps
medusajs/medusa pull request #137
Opened 2020-11-20 16:13 UTC by srindom

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/archive-order.js
> +    order = await orderService.decorate(order, [], ["region", "swaps"])
Decorate with customer

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/cancel-order.js
> +    order = await orderService.decorate(order, [], ["region", "swaps"])
decorate with customer

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/capture-payment.js
> +    order = await orderService.decorate(order, [], ["region", "swaps"])
customer

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/capture-swap.js
> +
Move to decorater

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/complete-order.js
> +    order = await orderService.decorate(order, [], ["region", "swaps"])
customer

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/create-fulfillment.js
> +    }
Remove

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/create-shipment.js
> +    order = await orderService.decorate(order, [], ["region", "swaps"])
customer

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/create-swap-shipment.js
> +    }
Remove

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/get-order.js
>        order.customer = await customerService.retrieve(order.customer_id)
Remove

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/index.js
> +  /**
Add cancel swap

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/receive-return.js
> +    order = await orderService.decorate(order, [], ["region", "swaps"])
Customer

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/receive-swap.js
> +    }
Remove

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/refund-payment.js
> +    order = await orderService.decorate(order, [], ["region", "swaps"])
Customer

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/request-return.js
> +    order = await orderService.decorate(order, [], ["region", "swaps"])
Customer

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/set-metadata.js
> +    order = await orderService.decorate(order, [], ["region", "swaps"])
Customer

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/admin/orders/update-order.js
> +    order = await orderService.decorate(order, [], ["region", "swaps"])
Customer

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/api/routes/store/swaps/index.js
> +  // route.get("/:id", middlewares.wrap(require("./get-swap").default))
Add get swap route

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/models/swap.js
> +    status: { type: String, default: "pending" },
Not being used

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/services/cart.js
> +        data.shipping_address = {
Add a test for this

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/services/order.js
> +  async registerSwapCreated(id, swapId) {
Add test for failure points

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/services/order.js
> +  async registerSwapReceived(id, swapId) {
Add test for failure points

2020-11-20 16:27 UTC, srindom commented on packages/medusa/src/services/order.js
> +    })
Add test for logic

2020-11-24 12:35 UTC, olivermrbl requested changes
Amazing job! 🏅 

We should consider adding a `DecoratorService` at some point?

2020-11-24 12:35 UTC, olivermrbl commented on packages/medusa-plugin-brightpearl/src/services/brightpearl.js
> +      paymentMethodCode: "1220",
Where does this number come from?

2020-11-24 12:35 UTC, olivermrbl commented on packages/medusa/src/api/routes/admin/customers/get-customer.js
> +    customer.orders = await Promise.all(customer.orders.map(async oId => {
Move this to `customerService.decorate` right? We want to be consistent.

2020-11-24 12:35 UTC, olivermrbl commented on packages/medusa/src/api/routes/admin/customers/update-customer.js
> +    data.orders = await Promise.all(
See comment above.

2020-11-24 12:35 UTC, olivermrbl commented on packages/medusa/src/services/return.js
> +    //return this.orderModel_
Remove

2020-11-24 13:02 UTC, merged