feature: allow disable ssl for minio
medusajs/medusa pull request #1439
Opened 2022-04-27 13:28 UTC by mtatheonly

allows disabling ssl for minio, for a local/docker installation without ssl enabled

2022-04-28 13:43 UTC, olivermrbl reviewed
question: Do you think we should enable SSL by default?

2022-04-28 13:43 UTC, olivermrbl commented on docs/content/how-to/uploading-images-to-minio.md
> +	sslEnabled: true || false, // if you're running locally with no ssl certificate, use false. Defaults to true if not set
issue: Should be snake_case like other options

2022-04-28 13:43 UTC, olivermrbl commented on packages/medusa-file-minio/README.md
> +  sslEnabled: [if ssl is enabled or not]
issue: Should be snake_case like other options

2022-04-28 13:43 UTC, olivermrbl commented on packages/medusa-file-minio/src/services/minio.js
> +    this.sslEnabled_ = ('sslEnabled' in options && options.sslEnabled !== undefined) ? options.sslEnabled : true
suggestion: I believe we could simplify this
```
this.sslEnabled = !!options?.sslEnabled
```

2022-04-29 12:11 UTC, mtatheonly commented
@olivermrbl, yes, I think it should be default

2022-05-08 11:22 UTC, olivermrbl requested changes

2022-05-08 11:22 UTC, olivermrbl commented on packages/medusa-file-minio/src/services/minio.js
> +    this.sslEnabled_ = !!options?.ssl_enabled
issue: Does not default to true even though documentation says so
```suggestion
    this.sslEnabled_ = options?.ssl_enabled ? options.ssl_enabled : false
```

2024-07-05 10:29 UTC, riqwan commented
Hey, thanks for the PR! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket.

2024-07-05 10:29 UTC, closed without merging