feat: claims
medusajs/medusa pull request #163
Opened 2021-02-01 16:00 UTC by srindom

Adds support for claims handling in Medusa.

**Behavior**

- Can behave in different ways:
    - Order was lost → Send replacement (`type: "replace"`, `item.reason: "missing_item"`)
    - Product has production failure → Record why, send replacement (`type: "replace"`)
        - Optionally send a return label (*select return address? → requires address settings)*
    - Customer prefers a refund → refund product amount (`type: "refund"`)
    - Order has wrong items → Recieve the wrong items and send new (`type: "replace"`, `item.reason: "wrong_item"`)

2021-02-01 20:12 UTC, olivermrbl requested changes
This is an amazing feature. Good job man!
Minor, minor comments...

2021-02-01 20:12 UTC, olivermrbl commented on packages/medusa/src/services/claim.js
> +        claimRepo.save(claim)
await

2021-02-01 20:12 UTC, olivermrbl commented on packages/medusa/src/services/claim.js
> +      const result = claimRepo.save(claim)
await

2021-02-01 20:12 UTC, olivermrbl commented on packages/medusa/src/services/claim.js
> +  setMetadata_(order, metadata) {
Remove as this is part of the base service

2021-02-02 16:50 UTC, srindom commented on packages/medusa/src/migrations/1612170081396-claims_1.ts
> +import { MigrationInterface, QueryRunner } from "typeorm"
agree

2021-02-02 16:50 UTC, srindom commented on packages/medusa/src/services/claim.js
> +        claimRepo.save(claim)
good catch

2021-02-03 08:49 UTC, merged