Log error if config file fails to load
medusajs/medusa pull request #1660
Opened 2022-06-14 15:50 UTC by magnusdr

This improves the developer experience.

If you add `throw new Error("You need to provide a JWT_SECRET")` inside `medusa-config.js`, you would get the following error:
```
TypeError: Cannot read properties of undefined (reading 'plugins')
```

Which is somewhat confusing at first sight.

I'm using `zod` to validate that required environment variables is set, and the errors are quite descriptive, so exposing them would be nice.

Maybe it would be better to not wrap the code in try catch block in the first place, since the catch block really doesn't do anything.

2022-06-19 12:16 UTC, olivermrbl requested changes
Thanks for this one @magnusdr! Have left a comment 👍

2022-06-19 12:16 UTC, olivermrbl commented on packages/medusa-core-utils/src/get-config-file.js
> +    console.errror(err)
issue: Typo in `errror`
```suggestion
    console.error(err)
```

2022-09-14 23:09 UTC, gefgu commented
@olivermrbl This pull request seems Ok. I think it only needs to be merged.

2022-11-25 21:36 UTC, magnusdr commented
I see this is not fixed somehow, my errors thrown inside `medusa-config.js` now gets printed out 👌

I'll close this PR then

2022-11-25 21:36 UTC, closed without merging