add images to product collections
medusajs/medusa pull request #1799
Opened 2022-07-05 19:24 UTC by edihasaj

add thumbnail and image properties to product-collection.ts.
add api endpoint changes for managing thumbnail and image.
add migration changes for product collection images
add new endpoint for querying collection with products and images included (joined) /store/collections/:id/products
add integration test for new created endpoint.
add docs changes for product-collection entity changes
add docs for the new added endpoint.

2022-07-05 19:25 UTC, edihasaj commented
@srindom Is this okay?

2022-07-06 12:42 UTC, kasperkristensen requested changes
I very much like the idea of adding images to collections! We could take it further by adding an optional `description`.  

I've added a couple of comments :)

2022-07-06 12:42 UTC, kasperkristensen commented on packages/medusa/src/services/product-collection.js
> +          productCollection.images = await this.upsertImages_(images)
You are re-implementing a method that already exists in the ImageRepository. 

Instead, you could just do like this:

```ts
const imageRepo = manager.getCustomRepository(this.imageRepository_)

// ...

if (images?.length) {
  productCollection.images = await imageRepo.upsertImages_(images)
}
```

2022-07-06 12:42 UTC, kasperkristensen commented on packages/medusa/src/services/product-collection.js
> +  async upsertImages_(images) {
No need for this method, as explained above.

2022-07-06 12:42 UTC, kasperkristensen commented on packages/medusa/src/services/product-collection.js
> +      }
```suggestion
     // at top of method
     const imageRepo = this.manager_.getCustomRepository(
          this.imageRepository_
      )
    
      if (images) {
          collection.images = await imageRepo.upsertImages_(images)
      }
```

2022-07-06 12:42 UTC, kasperkristensen commented on packages/medusa/src/services/product-collection.js
> +      if (!rest.thumbnail && images && images.length) {
nit

```suggestion
      if (!rest.thumbnail && images?.length) {
```

2022-07-06 23:17 UTC, edihasaj commented
I am also developing the remaining part in integrating medusa admin with the added functionality above.

2022-07-07 15:58 UTC, edihasaj commented
Requested functionality for querying imageRepository from DI, doesn't recognize the upsertImages() method, so I'm converting the services/product-collection.js to typescript. I'll test it and I'll let  you know for review continutation

2022-07-07 16:12 UTC, edihasaj commented
@kasperkristensen you can now review the changes.

2022-08-30 22:24 UTC, closed without merging