feat(medusa): Allowed regexp in cors
medusajs/medusa pull request #1935
Opened 2022-07-28 22:27 UTC by adrien2p

**What**
In some cases, a users that works with a bunch of subdomain would like to be able to configure the cors using a regexp to allow all or a sub set of his sub domains
https://discord.com/channels/876835651130097704/877195433649258536/1002330864216195112

2022-08-08 15:02 UTC, olivermrbl requested changes

2022-08-08 15:02 UTC, olivermrbl commented on packages/medusa-plugin-mailchimp/src/api/routes/index.js
> +import { parseCorsOrigins } from "@medusajs/medusa/dist/utils"
todo: Correct import
```suggestion
import { parseCorsOrigins } from "@medusajs/medusa"
```

Will probably require, that we expose our utils in `medusa/src/index.js`, but I believe that should be fine.

2022-08-08 15:02 UTC, olivermrbl commented on packages/medusa-payment-adyen/src/api/routes/hooks/index.js
> +import { parseCorsOrigins } from "@medusajs/medusa/dist/utils"
todo: Same as other comment

2022-08-08 15:02 UTC, olivermrbl commented on packages/medusa-plugin-mailchimp/src/api/routes/index.js
> +import { parseCorsOrigins } from "@medusajs/medusa/dist/utils"
Alternatively, we could move it to `medusa-core-utils`

2022-11-07 19:02 UTC, adrien2p commented
@olivermrbl do you think that pr could be merge at some point?

2022-11-07 20:30 UTC, olivermrbl commented
@adrien2p Yes, I will give this a review tomorrow :)

2022-11-15 08:00 UTC, olivermrbl commented
I am attempting to configure `ADMIN_CORS` with a regex, but I can't seem to make it work. Am I doing something wrong here?
```
const ADMIN_CORS = `/http\:\/\/localhost\:700\d/gm`
```

This should allow cors for e.g.`http://localhost:7000` and `http://localhost:7001`

2022-11-15 10:32 UTC, adrien2p commented
@olivermrbl I ve open a pr in the CORS repo as I can't seam to be able to find the culprit https://github.com/expressjs/cors/issues/292

2022-11-16 21:54 UTC, adrien2p commented
It is now working properly, just need to double the \ to avoid them to be escaped

2022-11-18 11:49 UTC, adrien2p commented
> That's a great functionality.
> 
> Question: I believe we will increase quite a lot the size of the plugins if they now depend on medusa core. Should we think about separating the "utils" to a new package? ps: considering that some people are not using package managers that reuse installed node_modules

I see what you mean, but plugins already depends on the core as they can extend strategies, interfaces, services, and also are already using some utilities. In that case I am afraid it would mean to separate all of those in different packages. Generally speaking, since the plugins have no dependency to the core, but only as a peer dependency, I don't think it is a problem. they are normally used in the server and the server install medusa core already wdyt?

2022-11-18 11:57 UTC, carlos-r-l-rodrigues commented
Sorry, disregard my comment. I see it's listed as peerDependencies. Even npm will reuse medusa-code if that's is installed.

2022-11-25 10:06 UTC, adrien2p commented
@olivermrbl finally all green

2022-11-28 10:50 UTC, olivermrbl commented
Think we should add a guide for this in our documentation. Wdyt? @adrien2p 

cc. @shahednasser

2022-11-28 10:51 UTC, adrien2p commented
Yes I agree, we can take the examples we've put in comments of that pr?

2022-11-28 10:53 UTC, shahednasser commented
I'll add an issue for it in Linear 👍🏻

2022-12-12 10:29 UTC, srindom commented
@olivermrbl, @adrien2p - can we merge this?

2022-12-12 10:31 UTC, olivermrbl commented
Yes, we were just awaiting a green pipeline. After resolving the conflict, we should be good 💪

2022-12-12 10:31 UTC, adrien2p commented
@srindom yes sure, i ve tested it and was waiting for someone else to test as well

2022-12-12 18:24 UTC, merged