feat(medusa-react): add collections batch endpoints
medusajs/medusa pull request #1959
Opened 2022-08-01 22:01 UTC by richardwardza

Depends on #1958 
Closes #1089 

Add POST/DELETE /admin/collections/:id/products/batch endpoints to @medusajs/medusa-react

(Not to be merged before #1958 )

I'm not sure how you would like to handle forks and stacked PR's..

2022-08-01 22:03 UTC, richardwardza commented on packages/medusa-js/src/resources/admin/collections.ts
> +   * @description Updates products associated with a Product Collection
The `description` and `param` description were copied from the API.

2022-08-04 13:47 UTC, adrien2p approved these changes
LGTM 🎉 small comments

2022-08-04 13:47 UTC, adrien2p commented on packages/medusa-react/mocks/handlers/admin.ts
> +        id: fixtures.get("product_collection").id,
todo: The id can be assigned with `req.params.id`

2022-08-04 13:47 UTC, adrien2p commented on packages/medusa-react/test/hooks/admin/collections/mutations.test.ts
> +})
todo: Missing eol

2022-08-07 11:26 UTC, olivermrbl requested changes

2022-08-07 11:26 UTC, olivermrbl commented on packages/medusa-react/src/hooks/admin/collections/mutations.ts
> +export const useAdminRemoveProductssFromCollection = (
todo: Typo in name
```suggestion
export const useAdminRemoveProductsFromCollection = (
```

2022-08-07 11:26 UTC, olivermrbl commented on packages/medusa-react/src/hooks/admin/collections/mutations.ts
> + * Hook returns functions for addition of multiple products to a collection.
todo: Minor fix to grammar
```suggestion
 * Hook returns function for adding multiple products to a collection.
```

2022-08-07 11:26 UTC, olivermrbl commented on packages/medusa-react/test/hooks/admin/collections/mutations.test.ts
> +describe("useAdminRemoveProductssFromCollection hook", () => {
todo: Typo
```suggestion
describe("useAdminRemoveProductsFromCollection hook", () => {
```

2022-08-07 11:26 UTC, olivermrbl commented on packages/medusa-react/test/hooks/admin/collections/mutations.test.ts
> +      () => useAdminRemoveProductssFromCollection(fixtures.get("product_collection").id),
```suggestion
      () => useAdminRemoveProductsFromCollection(fixtures.get("product_collection").id),
```

2022-08-07 14:33 UTC, richardwardza commented
Spelling and grammar updated, Thanks Oliver!

2022-08-07 14:52 UTC, richardwardza commented
I forgot the test - will update shortly.

2022-08-08 10:57 UTC, olivermrbl approved these changes
LGTM! Thanks again @richardwardza 💪

2022-08-08 10:58 UTC, merged