convert fulfillment service to typescript
medusajs/medusa pull request #1962
Opened 2022-08-02 05:08 UTC by pKorsholm

Fixes CORE-348

2022-08-04 13:41 UTC, adrien2p reviewed
Small comments :)

2022-08-04 13:41 UTC, adrien2p commented on packages/medusa-interfaces/src/fulfillment-service.js
> +    throw Error("validateFulfillmentData must be overridden by the child class")
todo: wrong method name in the error

2022-08-04 13:41 UTC, adrien2p commented on packages/medusa-interfaces/src/fulfillment-service.js
> +    throw Error("createOrder must be overridden by the child class")
todo: wrong method name in the error

2022-08-04 13:41 UTC, adrien2p commented on packages/medusa-interfaces/src/fulfillment-service.js
>      throw Error("createOrder must be overridden by the child class")
todo: wrong method name in the error

2022-08-04 13:41 UTC, adrien2p commented on packages/medusa/src/services/fulfillment-provider.ts
> +      const { fulfillmentProviderRepository } = this.container_
todo: this should be assigned on the correct property of the class and assigned in the constructor

2022-08-04 13:41 UTC, adrien2p commented on packages/medusa/src/services/fulfillment-provider.ts
> +    const { manager, fulfillmentProviderRepository } = this.container_
todo: this should be assigned on the correct property of the class and assigned in the constructor

2022-08-04 13:41 UTC, adrien2p commented on packages/medusa/src/services/fulfillment-provider.ts
> +      return this.container_[`fp_${provider_id}`]
todo: this should be the type of the container to restrict the access. You can look here https://github.com/medusajs/medusa/blob/master/packages/medusa/src/services/notification.ts#L20

2022-08-04 13:41 UTC, adrien2p commented on packages/medusa/src/services/fulfillment-provider.ts
> +  async canCalculate(option): Promise<boolean> {
todo: Missing typings

2022-08-04 13:41 UTC, adrien2p commented on packages/medusa/src/services/fulfillment-provider.ts
> +    cart: Order | Cart | undefined
suggestion: `cart?: Order | Cart`

2022-08-04 13:41 UTC, adrien2p commented on packages/medusa/src/services/fulfillment-provider.ts
> +   * @param {string} providerId - the id of the provider
suggestion: Remove the comments typings in favour of the one in the signature

2022-08-05 12:59 UTC, olivermrbl requested changes

2022-08-05 12:59 UTC, olivermrbl commented on packages/medusa/src/services/fulfillment-provider.ts
> +type NotificationProviderKey = `fp_${string}`
todo: Rename
```suggestion
type FulfillmentProviderKey = `fp_${string}`
```

2022-08-05 12:59 UTC, olivermrbl commented on packages/medusa/src/services/fulfillment-provider.ts
> +  [key in `${NotificationProviderKey}`]: BaseFulfillmentService
```suggestion
  [key in `${FulfillmentProviderKey}`]: BaseFulfillmentService
```

2022-08-05 12:59 UTC, olivermrbl commented on packages/medusa/src/services/fulfillment-provider.ts
> +    provider_ids: string[]
todo: Should be camelCased
```suggestion
    providerIds: string[]
```

2022-08-05 12:59 UTC, olivermrbl commented on packages/medusa/src/services/fulfillment-provider.ts
> +      provider_ids.map(async (p) => {
```suggestion
      providerIds.map(async (p) => {
```

2022-08-05 12:59 UTC, olivermrbl commented on packages/medusa/src/services/fulfillment-provider.ts
> +  retrieveProvider(provider_id: string): BaseFulfillmentService {
todo: Should be camelCased
```suggestion
  retrieveProvider(providerId: string): BaseFulfillmentService {
```

2022-08-05 12:59 UTC, olivermrbl commented on packages/medusa/src/services/fulfillment-provider.ts
> +      return this.container_[`fp_${provider_id}`]
```suggestion
      return this.container_[`fp_${providerId}`]
```

2022-08-05 12:59 UTC, olivermrbl commented on packages/medusa/src/services/fulfillment-provider.ts
> +        `Could not find a fulfillment provider with id: ${provider_id}`
```suggestion
        `Could not find a fulfillment provider with id: ${providerId}`
```

2022-08-22 17:19 UTC, olivermrbl approved these changes
LGTM!

2022-08-22 17:19 UTC, merged