Docs: Improve Docker documentation
medusajs/medusa pull request #2023
Opened 2022-08-10 08:02 UTC by Omar8345

I have made the doc to follow **the guidelines**, **updated commands (Docker)**, **added the doc to sidebar**.

Closes #1910 

@shahednasser Please check

2022-08-10 15:04 UTC, shahednasser requested changes
Thank you for your work @Omar8345 . I have left some comments below, but I have some additional comments:

- Add a Prerequisites section that Docker is required with a link to install it. (https://docs.docker.com/get-docker/)
- Remove Step 4 (configurations part)
- Add a Troubleshooting Section after the Testing section saying if the error `Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:5432 -> 0.0.0.0:0: listen tcp 0.0.0.0:5432: bind: address already in use` occurs they can change the port of postgres in `docker-compose.yml` to the following:

```yml
  postgres:
    ports:
      - "5433:5432"
```

- Copy the Additional Steps and What's Next sections from the quickstart guide into here
- There are a lot of changes in the `sidebar.js` file. This is likely due to configurations in your editor. Can you copy the current file in the `master` branch and just make one change to add the link?

2022-08-10 15:06 UTC, shahednasser commented on docs/content/quickstart/quick-start-docker.md
> +3. Seed your database with some entities, that will allow us to easily get started.
Actually remove number 3

2022-09-02 10:50 UTC, Omar8345 commented on docs/content/quickstart/quick-start-docker.md
> +Once done, your server will be accessible at `http://localhost:9000`.
LGFM!

2022-09-02 11:51 UTC, shahednasser commented on docs/content/quickstart/quick-start-docker.md
> +This quick start is intended for developers, assuming that you have already configured your local development environment and familiarised yourself with all the technologies and frameworks used throu
@Omar8345 why is this resolved?

2022-09-02 11:56 UTC, shahednasser commented
@Omar8345 I can see that you resolved comments without making the changes in those comments. Please make those changes then resolve the comments.

2022-09-13 08:07 UTC, closed without merging