docs: run migration before starting Medusa server
medusajs/medusa pull request #2113
Opened 2022-08-27 10:58 UTC by bytrangle

As I understand, the [Quickstart guide](https://docs.medusajs.com/quickstart/quick-start#create-a-medusa-server) for setting a Medusa server uses SQLite, so it doesn't mention running migrations before running `medusa develop`.

This may trip up users who use PostgreSQL. Because the Quickstart page is the only page on creating a Medusa server, I added a small reminder about running migrations after installing the server.

2022-08-27 16:12 UTC, bytrangle commented
I've changed the command to `yarn run seed`. This will run migrations if necessary, then seed the Postgres with dummy data. Without running it, when users run Gatsby storefront, it will fail because `gatsby-node.js` expects the GraphQL data to contain at least Medusa regions, products and collections.

2022-08-29 07:18 UTC, shahednasser requested changes
Thanks for the contribution @bytrangle and I think that's a great point! However, I think a better way to do this is in step 2. You can add a note after the block of code saying that the `--seed` option creates an SQLite database and seeds it, but if you're using PostgreSQL you have to run migrations (with the link to the migrations documentation).

As for the seed part related to Gatsby, let's move that into the Gatsby quickstart. You can add a note in the Prerequisites section saying that the Gatsby storefront expects to have at least one migration etc... So you can either add this data or seed your database with a link to [this documentation](https://docs.medusajs.com/cli/reference#seed).

If anything is not clear let me know ☺️

2022-08-30 07:15 UTC, bytrangle commented
@shahednasser Thank you so much for the feedback. Hope the new change is what you're looking for.

2022-08-30 07:18 UTC, shahednasser commented on docs/content/quickstart/quick-start.md
> +If you are using PostgreSQL, however, you need to [run migrations](../advanced/backend/migrations.md#how-to-run-migrations) right after creating the project and before starting the Medusa server.
```suggestion
If you are using PostgreSQL, however, you need to [run migrations](../advanced/backend/migrations.md#how-to-run-migrations) before starting the Medusa server.
```

2023-01-23 14:40 UTC, closed without merging