docs/Improve Docker Documentation
medusajs/medusa pull request #2248
Opened 2022-09-22 14:49 UTC by sabakhilji

issue# 1910

2022-09-23 15:09 UTC, shahednasser requested changes
Thank you @sabakhilji for your contribution! I added a few comments for changes below

2022-09-23 15:09 UTC, shahednasser commented on docs/content/quickstart/quick-start-docker.md
> +Running the above command does the following:
Add the following note before this:

~~~
:::note

If you get the error `ERROR: for postgres  Cannot start service postgres: Ports are not available`, change the ports used for PostgreSQL in `docker-compose.yml` to something like this:

```yml
  postgres:
    ports:
      - "5433:5433"
```

:::
~~~

2022-09-23 16:21 UTC, sabakhilji commented on docs/content/quickstart/quick-start-docker.md
> +If this is not the case, please head over to our [Getting Started](https://docs.medusajs.com/quickstart/quick-start) tutorial for a thorough walkthrough.
@shahednasser Do you want to delete both paragraphs "this quick start is intended.................................................  eco-system "and "If this is not the case................................walkthrough" please confirm.

2022-09-25 16:11 UTC, sabakhilji commented
@shahednasser please review the required changes and tell me if anything else is required. Thanks!

2022-09-26 07:37 UTC, shahednasser commented on docs/content/quickstart/quick-start-docker.md
> +```bash
Can you add a new line before this? Same with a new line after the closing backticks

2022-09-26 07:37 UTC, shahednasser commented on docs/content/quickstart/quick-start-docker.md
> +### Docker Desktop
Add a new line after this

2022-09-26 07:37 UTC, shahednasser commented on docs/content/quickstart/quick-start-docker.md
>  ## Introduction
I meant here to remove the Introduction section @sabakhilji

2022-09-26 08:04 UTC, shahednasser requested changes
Thanks @sabakhilji just a few more changes.

Additionally, can you add a sidebar item for this document? It should be added in `www/docs/sidebar.js` just after the current Quickstart link.

2022-09-26 08:04 UTC, shahednasser commented on docs/content/quickstart/quick-start-docker.md
> +You can test out your server using tools like Postman or sending a cURL request:
```suggestion
You can test out your server using tools like Postman or by sending a cURL request:
```

Sorry I made a small mistake on this one

2022-09-26 08:04 UTC, shahednasser commented on docs/content/quickstart/quick-start-docker.md
> +:::
Add a new line before this

2022-09-26 08:04 UTC, shahednasser commented on docs/content/quickstart/quick-start-docker.md
> +```bash
add a new line before this

2022-09-26 08:04 UTC, shahednasser commented on docs/content/quickstart/quick-start-docker.md
Remove this empty line

2022-09-26 14:33 UTC, sabakhilji commented
@shahednasser please review the changes . Thanks!

2022-09-26 15:09 UTC, shahednasser commented on docs/content/quickstart/quick-start-docker.md
@sabakhilji there's an empty line at the very beginning of the documentation please remove it

2022-09-26 15:11 UTC, shahednasser commented on www/docs/sidebars.js
> +       },
Please fix the indentation here to match the sibling items

2022-09-26 15:25 UTC, sabakhilji commented
done please check

On Mon, Sep 26, 2022 at 11:12 AM Shahed Nasser ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In www/docs/sidebars.js
> <https://github.com/medusajs/medusa/pull/2248#discussion_r980166004>:
>
> > +       {
> +          type:"doc",
> +          id: "quickstart w Docker",
> +          label :"Quickstart Docker",
> +       },
>
> Also, for the id property the value should be
> quickstart/quick-start-docker. And remove the label.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/medusajs/medusa/pull/2248#discussion_r980166004>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMPFB66AHKNSJIFZ3CVCU7TWAG4NFANCNFSM6AAAAAAQTEJDXQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-26 15:29 UTC, shahednasser requested changes

2022-09-26 15:29 UTC, shahednasser commented on www/docs/sidebars.js
> +          id: "quickstart w Docker",
for the id property the value should be `quickstart/quick-start-docker`

2022-09-26 15:29 UTC, shahednasser commented on www/docs/sidebars.js
> +          label :"Quickstart Docker",
Remove the label.

2022-09-27 11:11 UTC, shahednasser approved these changes

2022-09-27 11:12 UTC, merged

2022-09-27 11:12 UTC, shahednasser commented
Amazing work @sabakhilji thank you 🚀

2022-09-27 13:04 UTC, sabakhilji commented
thanks, @shahednasser for the guidance and support

2022-10-11 08:23 UTC, sabakhilji commented
done

On Mon, Sep 26, 2022 at 11:29 AM Shahed Nasser ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In www/docs/sidebars.js
> <https://github.com/medusajs/medusa/pull/2248#discussion_r980195872>:
>
> > @@ -30,6 +30,11 @@ module.exports = {
>            id: "quickstart/quick-start",
>            label: "Quickstart Guide",
>          },
> +        {
> +          type:"doc",
> +          id: "quickstart w Docker",
>
> for the id property the value should be quickstart/quick-start-docker
> ------------------------------
>
> In www/docs/sidebars.js
> <https://github.com/medusajs/medusa/pull/2248#discussion_r980195948>:
>
> > @@ -30,6 +30,11 @@ module.exports = {
>            id: "quickstart/quick-start",
>            label: "Quickstart Guide",
>          },
> +        {
> +          type:"doc",
> +          id: "quickstart w Docker",
> +          label :"Quickstart Docker",
>
> Remove the label.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/medusajs/medusa/pull/2248#pullrequestreview-1120459652>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMPFB632PTEMBAYIZMIDC7LWAG6ONANCNFSM6AAAAAAQTEJDXQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>