fix(medusa, medusa-js): Use price selection strategy for `GET /admin/variants`
medusajs/medusa pull request #2270
Opened 2022-09-28 16:54 UTC by kasperkristensen

**What**
- Adds the use of price selection strategy to the endpoint `GET /admin/variants`
- Updates medusa-js to reflect this change (expanding the parameters).

**Testing**
- Adds a new integration test validating that returned variants are now of type PricedVariant, with the expected fields: original_price, calculated_price, etc.

**Why**
- Our current RMA flows (in our admin dashboard) relied heavily on simply using `order.tax_rate` to calculate variant prices in the different RMA menus. As taxes in Medusa, have become feature complete this approach had become very naive and has several potential issues. Moving the responsibility for calculating the correct prices guarantees that we always show the correct prices to admins.

2022-09-28 19:16 UTC, olivermrbl requested changes
Overall great work! Have added a couple of comments here and there 👍

2022-09-28 19:16 UTC, olivermrbl commented on integration-tests/api/__tests__/admin/variant.js
> +    it("selects prices based on the passed currency code", async () => {
suggestion: We are only testing for the successful / expected case that is we've created a variant with id `test-variant` that only has prices in USD. 

To cover more cases, we should use a variant with prices in multiple different currencies.

2022-10-12 11:30 UTC, srindom approved these changes
LGTM!

2022-10-13 08:52 UTC, kasperkristensen commented
@olivermrbl could you also accept that the requested changes were addressed as it is blocking the PR from being merged 😄

2022-10-13 08:54 UTC, olivermrbl approved these changes
LGTM!

Sorry for the slow f/u @kasperkristensen 😅

2022-10-13 08:54 UTC, merged