docs: fixed issue #2325 and added additional step  for Gatsby and Next.js storefronts
medusajs/medusa pull request #2328
Opened 2022-10-03 10:35 UTC by ayushthe1

* What - Docs : added additional step for changing the directory to `my-medusa-storefront` for Gatsby and Next.js storefronts #2325 

* Why - In step 2 of `Installation` for [Gatsby](https://docs.medusajs.com/starters/gatsby-medusa-starter/#installation) and [Next.js](https://docs.medusajs.com/starters/nextjs-medusa-starter/#installation) Storefront ,it is mentioned to "change to the directory" but without that being portrayed in the command.
* How - Following the guideline in the issue made the changes to `medusa/docs/content/tutorial/0-set-up-your-development-environment.mdx`
* Testing - it's a markup file, so should not require anything other than manual testing.

2022-10-03 10:45 UTC, shahednasser requested changes
Thank you @ayushthe1 for your work, I've added some comments for fixes.

2022-10-03 10:45 UTC, shahednasser commented on docs/content/starters/gatsby-medusa-starter.md
>  ```
~~~suggestion
```bash
cd my-medusa-storefront
mv .env.template .env.development
```
~~~

2022-10-03 10:45 UTC, shahednasser commented on docs/content/starters/nextjs-medusa-starter.md
>  ```
~~~suggestion
```bash
cd my-medusa-storefront
mv .env.template .env.local
```
~~~

2022-10-03 10:45 UTC, shahednasser commented on docs/content/starters/nextjs-medusa-starter.md
> +3. Make sure the Medusa server is running, then run the local Next.js server:
Remove this change as it is being covered by another PR

2022-10-03 10:45 UTC, shahednasser commented on docs/content/starters/nextjs-medusa-starter.md
> +2. Change to the newly created directory `my-medusa-storefront` and rename the template environment variable file to use environment variables in development:
Remove the number change as it is being covered by another PR

2022-10-03 17:55 UTC, ayushthe1 reviewed
Fixed the issues as commented.

2022-10-03 17:57 UTC, ayushthe1 commented
@shahednasser i fixed the issues as commented by you. Can you please review it.

2022-10-04 07:24 UTC, shahednasser approved these changes

2022-10-04 07:32 UTC, merged

2022-10-04 07:32 UTC, shahednasser commented
Thanks! @ayushthe1 🚀

2022-10-04 07:46 UTC, ayushthe1 commented
Thanks @shahednasser  for your support .Please give me more issues to contribute. I would love to work more on this project.