Add missing import for add cart functionality file
medusajs/medusa pull request #2425
Opened 2022-10-12 10:38 UTC by Zeesky-code

- What - Solving PR https://github.com/medusajs/medusa/issues/2422

- Why -  There was a missing import for the Tabs and TabItem components that made the tabs not visible in the documentation.

- How - Following the guideline in the issue made the changes to medusa/docs/content/usage/configurations.md

- Testing - No test written because it's a markup file.

2022-10-12 12:17 UTC, shahednasser requested changes
Thank you for your contribution! It all looks great, but I just noticed that the `Update a Cart` section does not add tabs and instead just shows the code blocks. Can you change it to tabs similar to other sections in this page?

2022-10-12 14:38 UTC, Zeesky-code commented
> Thank you for your contribution! It all looks great, but I just noticed that the `Update a Cart` section does not add tabs and instead just shows the code blocks. Can you change it to tabs similar to other sections in this page?

Okay, I have done that.

2022-10-13 07:06 UTC, shahednasser requested changes

2022-10-13 07:06 UTC, shahednasser commented on docs/content/guides/carts-in-medusa.mdx
> +
Make sure this line doesn't have any spaces. It should be an empty line.
```suggestion

```

2022-10-13 07:06 UTC, shahednasser commented on docs/content/guides/carts-in-medusa.mdx
> +
```suggestion

```

2022-10-13 07:06 UTC, shahednasser commented on docs/content/guides/carts-in-medusa.mdx
> +
```suggestion

```

2022-10-13 07:06 UTC, shahednasser commented on docs/content/guides/carts-in-medusa.mdx
> +
```suggestion

```

2022-10-13 09:22 UTC, Zeesky-code commented on docs/content/guides/carts-in-medusa.mdx
> +
I have removed it.

2022-10-13 09:22 UTC, Zeesky-code commented on docs/content/guides/carts-in-medusa.mdx
> +
I have removed it.

2022-10-13 09:58 UTC, shahednasser approved these changes

2022-10-13 09:59 UTC, merged

2022-10-13 09:59 UTC, shahednasser commented
Thanks! @Zeesky-code 🚀