Feat(medusa): staging deployment action
medusajs/medusa pull request #2594
Opened 2022-11-11 09:33 UTC by pKorsholm

**What**
- Modify staging action to deploy staging versions on pushes to develop using the `staging` tag

**How**
- snapshot vs pre mode

I have chosen to not use the `pre`-mode that changesets provide and rather opt for the use of a snapshot release. I have chosen to do so because as far as I can tell a snapshot release fits our requirements, however it's a simpler procedure that relies more on changesets built-in features. Also using the `pre`-mode does come with a lot of warnings not to mess things up, whereas when using snapshot releases (as we already do), is much safer provided we always release using a tag.

- Not using the `changesets/action` github action

The `changesets/action` github action creates a pr that needs to can be, however when deploying a versioned staging version we dont want any package semver upgrades created from the `version` command to be preserved. To entirely prevent this the github action instead manually runs the process of deploying using changeset.

**Testing/Demo**
I have duplicated all medusa packages scoped to my npmjs account `@pkorsholm/` for testing. In my repo I have the action from this pr running on `pull_request` and it will deploy a staging package everytime a pr is changed. Feel free to test it out by creating a pr from from the master branch, removing endpoints or whatever (it just needs to build), and make a pr. All packages with changesets will be re-deployed under the tag `staging`. In your server you need to do a couple of steps because of how we run the medusa server: 
1. install packages with staging tag
  - all packages are prefixed scoped with `@pkorsholm`, if they were previously scoped to `@medusajs` they are now also scoped to `@pkorsholm`. 
2. In order to properly find the loaders duplicate the `@pkorsholm` folder in `./node_modules`
3. rename the folder `@pkorsholm - copy` to `@medusajs` (this is where the loaders will be loaded from
4. move packages that are not `medusa` and `medusa-cli` from the newly created `@medusajs` folder into `node_modules`
5. run you server

repeat 1-5 after release of a new package under the staging tag (only required because i renamed all packages)

Fixes CORE-747

2022-11-14 09:24 UTC, olivermrbl requested changes
Super nice @pKorsholm! Have left a couple of comments.

2022-11-14 09:24 UTC, olivermrbl commented on .github/workflows/staging-release.yml
> +      - name: Install Dependencies build
todo: Rename action step
```suggestion
      - name: Build all packages
```

2022-11-14 09:24 UTC, olivermrbl commented on .github/workflows/staging-release.yml
> +      - name: version staging packages
comment: This is very nit, but just want to stay consistent 😅 
```suggestion
      - name: Version staging packages
```

2022-11-14 09:24 UTC, olivermrbl commented on .github/workflows/staging-release.yml
> +      - name: publish staging packages
comment: Same here 😄 
```suggestion
      - name: Publish staging packages
```

2022-11-14 09:24 UTC, olivermrbl commented on .github/workflows/staging-release.yml
> +        run: yarn release:staging
thought: I believe we must run an install after versioning to ensure the lockfile is refreshed with the latest staging versions. I've encountered issues around this when running manual releases.

2022-11-14 09:24 UTC, olivermrbl commented
> Should we remove the old staging packages when deploying a new one in order to not clog our versions on npmjs?
npmjs has an api we could use

I think this should be left for a follow-up later on. Will open an issue for it 👍

2022-11-14 09:49 UTC, pKorsholm commented
Closing this for now in order to include ticket mentioned by @olivermrbl

2022-11-16 02:09 UTC, pKorsholm commented
Re-opening this after initial investigation into unpublishing previous versions. 

The initial conclusion is that it's not possible to unpublish a given version of a package if another package depends on _any_ version of the package. Future investigations will be into publishing packages under a different organisation intended for staging only, but will be postponed until after an initial version of the staging environment is functional.

2022-11-16 19:08 UTC, olivermrbl approved these changes
LGTM!

2022-11-16 19:08 UTC, merged