feat(medusa): allow creating draft orders without requiring an email address
medusajs/medusa pull request #2704
Opened 2022-11-30 10:25 UTC by josetr

Please let me know if I need to make changes in more places altho I can't build the project due to #2703

2022-12-05 16:22 UTC, adrien2p requested changes

2022-12-05 16:22 UTC, adrien2p commented on packages/medusa/src/api/routes/admin/draft-orders/create-draft-order.ts
>    email: string
suggestion: Missing `?`

2022-12-05 16:22 UTC, adrien2p commented on packages/medusa/src/api/routes/admin/draft-orders/create-draft-order.ts
>   *     application/json:
Question: would it required some other changes around the service layer as well?

2023-07-18 13:31 UTC, langovoi commented
Any updates here?

2023-09-10 19:37 UTC, josetr commented
@olivermrbl @adrien2p can you guys take a look at this one and #2714 again?

2023-11-28 18:11 UTC, josetr commented
🙏

2024-07-05 10:37 UTC, riqwan commented
Hey, thanks for the PR! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket.

2024-07-05 10:37 UTC, closed without merging