docs: Update netlify deploy readme for clarity
medusajs/medusa pull request #2748
Opened 2022-12-09 06:08 UTC by komali2

It was unlcear why "Gatsby" was mentioned in the env name for the server URL. Also, the code shows precedence given to `MEDUSA_BACKEND_URL` now:

```
    __MEDUSA_BACKEND_URL__: JSON.stringify(
      env.MEDUSA_BACKEND_URL ||
        // Backwards-compat with Gatsby.
        env.GATSBY_MEDUSA_BACKEND_URL ||
        env.GATSBY_STORE_URL ||
        ""
    ),
```

Therefore, this should be indicated in the documentation.

2022-12-09 08:36 UTC, shahednasser requested changes
Thank you for making this change! I've added some comments below

2022-12-09 08:36 UTC, shahednasser commented on docs/content/deployments/admin/deploying-on-netlify.md
>  netlify env:set GATSBY_MEDUSA_BACKEND_URL "<YOUR_SERVER_URL>"
```suggestion
netlify env:set MEDUSA_BACKEND_URL "<YOUR_SERVER_URL>"
```

2022-12-09 08:36 UTC, shahednasser commented on docs/content/deployments/admin/deploying-on-netlify.md
> +If you define multiple environment variables with the above names, precedence will be given to `MEDUSA_BACKEND_URL`, and the others will be ignored (even if `MEDUSA_BACKEND_URL` is an invalid URL).
Let's revert this back to the text that was before "Where `<YOUR_SERVER_URL>` is the URL of your Medusa server." and instead add a [note](https://docs.medusajs.com/contribution-guidelines/#notes-and-additional-information) saying something like "Previous versions of the Medusa admin use `GATSBY_MEDUSA_BACKEND_URL` or `GATSBY_STORE_URL`. Although the Admin is backwards compatible, it is advised to change the variable to `MEDUSA_BACKEND_URL`".

2022-12-12 17:10 UTC, shahednasser commented
@komali2 any update on this? 😊

2022-12-13 08:16 UTC, merged

2023-03-01 09:11 UTC, komali2 commented
Thanks for adding changes! I got overwhelmed at work.