initial options proposal
medusajs/medusa pull request #2809
Opened 2022-12-15 11:26 UTC by pKorsholm

2022-12-15 11:26 UTC, pKorsholm commented
/snapshot-this

2022-12-15 11:37 UTC, pKorsholm commented
/snapshot-this

2022-12-16 09:14 UTC, adrien2p approved these changes
Should we update the readme to reflect those changes?

2022-12-16 12:11 UTC, shahednasser requested changes
Made some changes to the documentation based on our writing/style guide, hope that's fine 😄. If there are inaccuracies feel free to make the necessary changes.

2022-12-16 12:11 UTC, shahednasser commented on docs/content/add-plugins/s3.md
> +```
~~~suggestion
### Add AWS Configurations

You can pass AWS configurations in the plugin's options under the property `aws_config_object`. This property is an object that accepts [AWS Configurations](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html) as its properties.

For example, you can pass the `region`, `access_key_id` and `secret_access_key` in `aws_config_object`:

```jsx title=medusa-config.js
const plugins = [
  //...
  {
    resolve: `medusa-file-s3`,
    options: {
        s3_url: process.env.S3_URL,
        bucket: process.env.S3_BUCKET,
        aws_config_object: {
          region: process.env.S3_REGION,
          access_key_id: process.env.S3_ACCESS_KEY_ID,
          secret_access_key: process.env.S3_SECRET_ACCESS_KEY,
        }
    },
  },
];
```

Make sure to define `S3_REGION`, `S3_ACCESS_KEY_ID`, and `S3_SECRET_ACCESS_KEY` in your environment variables first.

~~~

2022-12-20 08:49 UTC, shahednasser approved these changes

2022-12-20 08:56 UTC, olivermrbl approved these changes
LGTM!

2022-12-20 09:01 UTC, merged