feat(medusa): add has_account to possible list_customers query params
medusajs/medusa pull request #2811
Opened 2022-12-15 14:46 UTC by pKorsholm

**What**
- Add `has_account` as a possible query parameter for list-customers

2022-12-15 14:47 UTC, pKorsholm commented
/snapshot-this

2022-12-15 18:56 UTC, olivermrbl requested changes

2022-12-15 18:56 UTC, olivermrbl commented on packages/medusa/src/types/customers.ts
> +  @Transform(({ value }) => value === "true")
todo: Use our custom boolean validator
```suggestion
  @Transform(({ value }) => optionalBooleanMapper.get(value))
```

2022-12-16 09:13 UTC, adrien2p approved these changes
LGTM 🎉

2022-12-16 11:16 UTC, olivermrbl approved these changes
LGTM!

2022-12-16 11:16 UTC, merged