Fix/create customer in draft order
medusajs/medusa pull request #285
Opened 2021-06-17 09:51 UTC by sebastiannicolajsen

2021-06-18 09:07 UTC, srindom reviewed
what is the idea here? :)

2021-06-24 06:11 UTC, sebastiannicolajsen commented
@srindom updated description

2021-06-28 18:37 UTC, srindom commented
Can we make the customer part of the `create` method instead of having to make two calls to the cart service :)

2021-07-09 10:17 UTC, srindom requested changes
Can you add a unit and integration test for this please :)

2021-07-09 10:17 UTC, srindom commented on packages/medusa/src/services/cart.js
> +          .withTransaction(this.transactionManager_)
should use `manager` instead of `this.transactionManager_`

2021-07-14 07:21 UTC, srindom requested changes

2021-07-14 07:21 UTC, srindom commented on packages/medusa/src/services/cart.js
> +    return customer
This is not used

2021-08-17 13:49 UTC, srindom submitted a review, later dismissed

2021-08-17 13:49 UTC, srindom commented on packages/medusa-payment-manual/services/manual-payment.js
> +"use strict";
Should be `.gitignore`d

2021-09-07 09:08 UTC, srindom approved these changes

2021-09-07 09:15 UTC, srindom approved these changes

2021-09-07 09:15 UTC, merged