Fix/issue 2938
medusajs/medusa pull request #2941
Opened 2023-01-04 18:12 UTC by RegisHubelia

This PR fixes an issue where gift card created from the admin portal wouldn't send using sendgrid.

Also - there is no order attached to the gift card when it's created trough the admin portal - so I revoved the return statement if there is no order and adjusted the data sent to the template based on what was there - I updated the documentation to reflect the "display_value".

2023-01-09 12:36 UTC, RegisHubelia commented
Can someone look at this PR and let me know if any changes is required?

Thanks

2023-01-11 13:18 UTC, olivermrbl requested changes
Thanks for your contribution. I've added a couple of todo. Let me know if something is unclear :)

2023-01-11 13:18 UTC, olivermrbl commented on packages/medusa-plugin-sendgrid/src/services/sendgrid.js
> +      display_value: (giftCard.value * (1 + taxRate) / 100).toFixed(2),
todo: Use util to cover all currency cases
```suggestion
      display_value: `${this.humanPrice_((giftCard.value * 1+ taxRate), giftCard.region.currency_code)} ${giftCard.region.currency_code}`,
```

2023-01-11 13:18 UTC, olivermrbl commented on packages/medusa-plugin-sendgrid/src/services/sendgrid.js
> +    // Should this use the custom Tax Provider if any?
todo: Remove comment

2023-01-11 15:41 UTC, RegisHubelia commented
Perfect  - will do and send the commit shortly.

2023-01-11 23:15 UTC, daysgobye commented
Thank you for catching this. Glad someone is working on it cant wait for it to be merged.

2023-01-17 10:58 UTC, RegisHubelia commented on packages/medusa-plugin-sendgrid/src/services/sendgrid.js
> +    // Should this use the custom Tax Provider if any?
Done!

2023-01-17 10:58 UTC, RegisHubelia commented
> Also, please add a [changeset](https://github.com/changesets/changesets) bumping the Sendgrid plugin with the following message:
> 
> ```
> fix(medusa-plugin-sendgrid): Inject GiftCardService to eliminate undefined error
> ```

Done

2023-01-23 15:21 UTC, RegisHubelia commented
@olivermrbl - Let me know if I need to do anything else?

2023-01-23 16:08 UTC, olivermrbl commented
@RegisHubelia Your branch is out-of-date with the base. Can I get you to update?

2023-01-23 17:11 UTC, RegisHubelia commented
@olivermrbl 
> @RegisHubelia Your branch is out-of-date with the base. Can I get you to update?

Just did!

2023-01-23 18:42 UTC, olivermrbl approved these changes
LGTM! Will be part of next release :)

2023-01-27 21:07 UTC, daysgobye commented
what is eta on this being merged?

2023-01-30 08:53 UTC, olivermrbl commented
@RegisHubelia Can I get you to update your branch with latest from `develop`? Then I'll push to get it merged today :)

2023-01-30 11:12 UTC, RegisHubelia commented
> @RegisHubelia Can I get you to update your branch with latest from `develop`? Then I'll push to get it merged today :)

Done!

2023-01-30 12:11 UTC, merged