chore(oas): replace response with $ref class JSDoc (Store PRO-V)
medusajs/medusa pull request #3044
Opened 2023-01-16 19:33 UTC by patrick-medusajs

### Scope

Store routes directories PRO to V.

### What

Move inline OAS response schema declaration under their respective class declarations in order to expose them through  `#/components/schemas`. Replace inline OAS response schema with a `$ref` reference pointing to the newly declared schema.

### Why

Having response declared as its own "named" schema will allow OAS code generators to output typed entities/DTO that can be consumed without having to reference the route/operation.

### How

Declare a new @schema JSDoc for each "Res" class used to parse and validate request body. Move the current inline requestBody to the new @schema.

### Test

- Ran OAS validator.
- Ran docs build script.

Expect no visible changes to the documentation.

2023-01-16 19:44 UTC, patrick-medusajs reviewed
self-review: highlighting noteworthy code changes.

Should also resolve DOCS-217

2023-01-16 19:44 UTC, patrick-medusajs commented on packages/medusa/src/api/routes/store/product-categories/index.ts
> +}
Added missing declaration.

2023-01-16 19:44 UTC, patrick-medusajs commented on packages/medusa/src/api/routes/admin/products/index.ts
> + *         - $ref: "#/components/schemas/PricedProduct"
Now matches the typed response.
https://github.com/medusajs/medusa/blob/4424301ae27ea0dbcd97bb284462e56ce2a52698/packages/medusa/src/api/routes/admin/products/index.ts#L227-L229

2023-01-16 19:44 UTC, patrick-medusajs commented on packages/medusa/src/api/routes/store/products/list-products.ts
> - *                             - $ref: "#/components/schemas/ProductVariantPricesFields"
Replace with PricedProduct

2023-01-16 19:44 UTC, patrick-medusajs commented on packages/medusa/src/api/routes/store/variants/get-variant.ts
> - *                 - $ref: "#/components/schemas/ProductVariantPricesFields"
Replace with PricedVariant.
https://github.com/medusajs/medusa/blob/4424301ae27ea0dbcd97bb284462e56ce2a52698/packages/medusa/src/types/pricing.ts#L37-L79

2023-01-16 19:44 UTC, patrick-medusajs commented on packages/medusa/src/api/routes/store/variants/index.ts
> +export type StoreVariantsListRes = {
Endpoint does not return PaginatedResponse fields. Removed from typing.

2023-01-16 19:44 UTC, patrick-medusajs commented on packages/medusa/src/api/routes/store/variants/list-variants.ts
> - *                   - $ref: "#/components/schemas/ProductVariantPricesFields"
Replace with PricedVariant

2023-01-16 19:44 UTC, patrick-medusajs commented on packages/medusa/src/models/product-variant.ts
> - * @schema ProductVariantPricesFields
OAS was folded under PricedVariant

2023-01-16 22:48 UTC, olivermrbl approved these changes
LGTM!

2023-01-17 07:27 UTC, fPolic approved these changes
LGTM!

2023-01-17 08:19 UTC, shahednasser requested changes
Just a small comment 🙂

2023-01-17 08:19 UTC, shahednasser commented on packages/medusa/src/api/routes/store/product-types/index.ts
> + *     $ref: "#/components/schemas/ProductType"
Should be an array

2023-01-17 09:24 UTC, pKorsholm approved these changes
LGTM

2023-01-17 14:22 UTC, shahednasser approved these changes

2023-01-17 14:22 UTC, merged