fix(medusa): Received quantity on return lines
medusajs/medusa pull request #3267
Opened 2023-02-15 11:03 UTC by olivermrbl

2023-02-16 08:13 UTC, olivermrbl commented
Changing base to `master` to include in hotfix patch

2023-02-16 15:29 UTC, kasperkristensen approved these changes
LGTM

2023-02-17 08:23 UTC, olivermrbl commented
@adrien2p Will you give this a review? Shouldn't take long :)

2023-02-17 08:31 UTC, adrien2p requested changes
few changes in the test and it should be good to go 🚀

2023-02-17 08:31 UTC, adrien2p commented on integration-tests/api/__tests__/admin/returns.js
> +    it.only("should receive a return partially", async () => {
todo: rm only

2023-02-17 08:31 UTC, adrien2p commented on integration-tests/api/__tests__/admin/returns.js
> +          {
todo: Move that to a const at the before the main describe

2023-02-17 08:31 UTC, adrien2p commented on integration-tests/api/__tests__/admin/returns.js
> +        .catch((e) => console.log(e))
todo: rm

2023-02-17 08:31 UTC, adrien2p commented on integration-tests/api/__tests__/admin/returns.js
> +            headers: {
todo: use the const mentionned before

2023-02-17 08:31 UTC, adrien2p commented on integration-tests/api/__tests__/admin/returns.js
> +        .catch((e) => console.log(e))
todo: rm

2023-02-17 08:31 UTC, adrien2p commented on integration-tests/api/__tests__/admin/returns.js
> +      const receivedItem = receivedReturn.items[0]
suggestion: should we expect the length?

2023-02-17 09:37 UTC, adrien2p commented on integration-tests/api/__tests__/admin/returns.js
> +      expect(receivedReturn.items.length).toEqual(1)
todo: this expect should happen before line 275 to ensure we get the right one

2023-02-17 09:38 UTC, adrien2p approved these changes
One last change, LGTM

2023-02-17 10:13 UTC, merged