docs: Plugin overview
medusajs/medusa pull request #327
Opened 2021-08-01 10:33 UTC by olivermrbl

Adds a guide containing the following:
- Plugin overview
- What is a plugin?
- Building a plugin
- Implementation
- Publishing
- Installation and configuration

2021-08-01 13:12 UTC, FuzzyReason commented on docs/content/tutorials/plugins.md
> +```jsx
js? Not a React functionality :)

2021-08-02 11:26 UTC, srindom requested changes

2021-08-02 11:26 UTC, srindom commented on docs/content/tutorials/plugins.md
> +We've already gone through the process of building custom services, endpoints, and subscribers in another tutorial, so this will not be repeated. The process is the same for the logic within a plugin
We will take the custom functionality we created in the tutorial and make a plugin that others can easily install so they can welcome new customers to their Medusa store.

2021-08-02 11:26 UTC, srindom commented on docs/content/tutorials/plugins.md
> +
Maybe explain in a few more steps what should be done here:

- Explain that reader should copy the `/services/welcome.js`, `/api/index.js` and `/subscribers/welcome.js` files from tutorial and add them to `/src`
- Maybe provide a tree dump that shows which files make up the plugin directory.

2021-08-02 11:26 UTC, srindom commented on docs/content/tutorials/plugins.md
> +Official Medusa plugins can be found within the mono repo `@medusajs/medusa/packages/` and community plugins can be found by searching NPM for keywords such as `medusa` or `medusa-plugin`.
within [the mono repo](link)

2021-08-02 11:26 UTC, srindom commented on docs/content/tutorials/plugins.md
> +      redis_url: REDIS_URL,
I actually don't think we use the `redis_url` in the Contentful plugin anymore

2021-08-03 06:51 UTC, olivermrbl commented
Note to self (and others): Don't expect Notion markdown export to follow correct format :)

2021-08-03 06:54 UTC, FuzzyReason commented
> Note to self (and others): Don't expect Notion markdown export to follow correct format :)

https://dillinger.io/ This is a tool I love to use when I need to see the formatted markdown which works for Github :)

2021-08-05 08:40 UTC, srindom approved these changes

2021-08-05 08:41 UTC, merged