add guard to return early
medusajs/medusa pull request #3365
Opened 2023-03-03 09:02 UTC by pKorsholm

**What**
- return early if no locations are passed along to query by when getting quantities for inventory items

**Why**
- `where location_id in ()` is not valid sql syntax and causes a 500 to be raised.
- if there are no specified locations the result should be 0

Fixes CORE-1178

2023-03-03 09:22 UTC, adrien2p requested changes

2023-03-03 09:22 UTC, adrien2p commented on packages/inventory/src/services/inventory-level.ts
> +    if(locationIds.length === 0) {
suggestion: `if (!locationIds.length)`

2023-03-03 09:22 UTC, adrien2p commented on packages/inventory/src/services/inventory-level.ts
> +    if(locationIds.length === 0) {
suggestion: `if (!locationIds.length)`

2023-03-03 09:22 UTC, adrien2p commented on packages/inventory/src/services/inventory-level.ts
> +    if(locationIds.length === 0) {
suggestion: `if (!locationIds.length)`

2023-03-07 10:24 UTC, srindom commented
@pKorsholm can you take a look at @adrien2p's comments so we can get this merged :)

2023-03-07 11:03 UTC, adrien2p approved these changes

2023-03-07 11:19 UTC, merged