fix: make shipping_option_id on requirements optional
medusajs/medusa pull request #340
Opened 2021-08-17 09:35 UTC by kasperkristensen

**What**
- Changed validator in update-shipping-profile (route `POST admin/shipping-options/:id`).
- `shipping_profile_id` on `requirements` is now optional, which allows the correct behaviour of if no `id` is provided a new requirement is created on the `Shipping Profile`.

**Why**
- It is currently not possible to update the requirements of a shipping option in the admin system, if it was not originally created with a set of requirements.
- This change makes it possible  to create a shipping option with no requirements and then later add requirements if needed.

**How**
- Simple change to the validation schema found in `POST admin/shipping-options/:id`.

**Testing**
- Integration test that validates that when a/multiple requirements are part of an update to a `Shipping Option` with no prior requirements, they are successfully added to the object.

2021-08-17 14:00 UTC, srindom requested changes
Some quick fixes :p

2021-08-18 12:59 UTC, kasperkristensen commented on packages/medusa/src/services/shipping-option.js
>        const result = await optionRepo.save(option)
When trying to update with a single requirement (meaning that if there
was previously two, there should now only be one) it fails with the following
Postgres/TypeOrm error "null value in column 'shipping_option_id' of relation
'shipping_option_requirement' violates not-null constraint". I have tried to
perform a remove on the requirement that should no longer be used, using the
requirementRepo, before saving the option but the error still occurs.

any ideas on how I can fix this? @olivermrbl @srindom

2021-09-01 09:35 UTC, olivermrbl approved these changes
Great work!

2021-09-09 07:02 UTC, srindom approved these changes

2021-09-09 07:03 UTC, merged