Chore/bump bull
medusajs/medusa pull request #3415
Opened 2023-03-08 10:16 UTC by olivermrbl

**What**
- Bumps `bull` on `v1.7.*` to allow existing users to leverage advanced job options: https://github.com/OptimalBits/bull/releases/tag/v4.4.0
- As a bonus, introduces TS types to `bull` package: https://github.com/OptimalBits/bull/releases/tag/v4.10.0

2023-03-08 15:40 UTC, olivermrbl commented on packages/medusa-react/jest.config.js
> +    ".(ts|tsx|ts)$": ["ts-jest", { isolatedModules: true, diagnostics: false }],
self-review: `globals` is deprecated

2023-03-08 15:40 UTC, olivermrbl commented on integration-tests/helpers/use-redis.ts
> +        maxRetriesPerRequest: null,
self-review: https://github.com/OptimalBits/bull/releases/tag/v4.0.0

2023-03-08 16:23 UTC, adrien2p requested changes

2023-03-08 16:23 UTC, adrien2p commented on .changeset/cuddly-keys-rescue.md
> +Bump `bull` package
suggestion: `chores(medusa): ...`

2023-03-08 16:23 UTC, adrien2p commented on integration-tests/helpers/use-redis.ts
> +        maxRetriesPerRequest: null,
So apparently 20 wasn't enought?

2023-03-08 16:23 UTC, adrien2p commented on packages/medusa-react/jest.config.js
> +    ".(ts|tsx|ts)$": ["ts-jest", { isolatedModules: true, diagnostics: false }],
todo: ts is mentionned twice, should remove one of them

2023-03-08 16:23 UTC, adrien2p commented on packages/medusa-react/jest.config.js
> -    // Force module uuid to resolve with the CJS entry point, because Jest does not support package.json.exports. See https://github.com/uuidjs/uuid/issues/451
suggestion: should we instead have `transformIgnorePatterns: ['/node_modules/'],` as far as I know, there is not reason to have to transform any node modules package right?

2023-03-08 16:23 UTC, adrien2p commented on packages/medusa/src/loaders/redis.ts
> +    const client = new RealRedis(configModule.projectConfig.redis_url, {
todo: store the config into a const and then pass it to client/subscriber

2023-03-08 16:23 UTC, adrien2p commented on packages/medusa/src/services/event-bus.ts
> +        ...(opts as any),
todo: we should cast with the expected type instead of any right? is there any typing issues when we don't cast?

2023-03-14 07:42 UTC, olivermrbl commented
Moving these changes to `develop`, as the recent addition of global options should suffice for users running with v1.7.*

2023-03-14 07:42 UTC, closed without merging