fix(admin-ui): Gift Card manage page
medusajs/medusa pull request #3532
Opened 2023-03-20 22:45 UTC by kasperkristensen

WIP

2023-03-21 19:04 UTC, olivermrbl requested changes
This is much better - great work @kasperkristensen. Left a couple of todos 👍 

@StephixOne will you give this a review too?

2023-03-21 19:04 UTC, olivermrbl commented on packages/admin-ui/ui/src/components/forms/product/organize-form/index.tsx
> +      categoriesOptions.length === 0 ? (
todo: Looks like this should check should be flipped? 
```suggestion
      categoriesOptions?.length ? (
```

2023-03-21 19:04 UTC, olivermrbl commented on packages/admin-ui/ui/src/domain/gift-cards/manage/index.tsx
> +        path="/a/products"
todo:
```suggestion
        path="/a/gift-cards"
```

2023-03-22 07:39 UTC, olivermrbl approved these changes
LGTM - pending @StephixOne's approval :)

2023-03-22 23:35 UTC, StephixOne approved these changes
LGTM 👍

2023-03-23 08:29 UTC, merged