Feat(medusa): remove created reservations on subsequent failure for cart completion
medusajs/medusa pull request #3554
Opened 2023-03-22 13:06 UTC by pKorsholm

**What**
- If cart completion fails after creating reservations, remove those reservations

**Why**
- To avoid hanging reservations if something fails at a later point

2023-03-24 15:36 UTC, srindom requested changes
Please add an integration test.

2023-03-28 20:15 UTC, olivermrbl commented
@srindom Will you give this a second review? 🙏

2023-03-28 22:13 UTC, srindom approved these changes
LGTM w. comments.

2023-03-29 14:42 UTC, pKorsholm commented on integration-tests/plugins/__tests__/inventory/cart/cart.js
> +      })
Added it here 😄 it was just adding a case to the exception formatter, but we should do some extensive exploration into different postgres error codes. This was cause by trying to complete an order without a customer which yielded no clear error message, however it should 😄

2023-03-29 17:03 UTC, merged