docs: Add upgrade guide for Algolia plugin
medusajs/medusa pull request #3582
Opened 2023-03-25 17:22 UTC by olivermrbl

**What**
Upgrade guide for Algolia serach plugin

Solves DOCS-665

2023-03-25 17:22 UTC, olivermrbl commented
Exact version still to be decided. Please keep as draft until then :)

2023-03-27 07:39 UTC, olivermrbl commented
@shahednasser first time I see this:
<img width="594" alt="CleanShot 2023-03-27 at 09 39 11@2x" src="https://user-images.githubusercontent.com/59018053/227873391-ec17bfa0-802a-40bb-a4a1-25b495d33fbb.png">


That is really nifty! 💯

2023-03-27 07:40 UTC, shahednasser commented on docs/content/upgrade-guides/plugins/algolia/1-0-0.md
> +Version 1.0.0 of our official Algolia plugin, `medusa-plugin-algolia` comes with breaking changes to the plugin options that are passed to the Algolia service through `medusa-config.js`.
```suggestion
Version 1.0.0 of the official Algolia plugin comes with breaking changes to the plugin options that are passed to the Algolia service through `medusa-config.js`.
```

2023-03-27 07:42 UTC, shahednasser commented on docs/content/upgrade-guides/plugins/algolia/1-0-0.md
> +```
~~~suggestion
```js title=medusa-config.js
const plugins = [
  // ...
  {
    applicationId: string
    adminApiKey: string
    settings: {
      indexName: {
        indexSettings: {
          searchableAttributes: string[]
          attributesToRetrieve: string[]
          // ...
        }
        transformer?: (product) => ({
          id: product.id,
          // ...
        })
      }
    }
  }
]
```
~~~

2023-03-27 07:46 UTC, shahednasser requested changes
Similar suggestions to the MeiliSearch plugin. Would be great to also run the eslint command to fix eslint errors 😇

2023-03-27 07:46 UTC, shahednasser commented on docs/content/upgrade-guides/plugins/algolia/1-0-0.md
> +```
~~~suggestion
```js title=medusa-config.js
const plugins = [
  // ...
  {
    application_id: "someId",
    admin_api_key: "someApiKey",
    settings: {
      // example
      products: {
        searchableAttributes: ["title", "description"],
        attributesToRetrieve: ["title", "description"],
      }
    }
  }
]
```
~~~

2023-03-27 07:46 UTC, shahednasser commented on docs/content/upgrade-guides/plugins/algolia/1-0-0.md
> +In the above example, an index `products` has been configured with two options. Updating to 1.0.0 requires you to nest these within the `indexSettings`. Additionally, we recommend updating your admin
```suggestion
In the above example, an index `products` has been configured with two options `searchableAttributes` and `attributesToRetrieve`. Updating to v1.0.0 requires you to nest these within the `indexSettings`. Additionally, the admin API key and application ID options should now be in camel case, as the snake-cased version will be deprecated. 
```

2023-03-27 07:46 UTC, shahednasser commented on docs/content/upgrade-guides/plugins/algolia/1-0-0.md
> +```
~~~suggestion
```js title=medusa-config.js
const plugins = [
  // ...
  {
    applicationId: "someId",
    adminApiKey: "someApiKey",
    settings: {
      products: {
        indexSettings: {
          searchableAttributes: ["title", "description"],
          attributesToRetrieve: ["title", "description"],
        }
      }
    }
  }
]
```
~~~

2023-03-27 07:46 UTC, shahednasser commented on docs/content/upgrade-guides/plugins/algolia/1-0-0.md
> +You can read more about the new plugin options properties in the package README.
```suggestion
You can learn more about the new plugin options in the [Algolia plugin documentation](../../../plugins/search/algolia.md).
```

2023-03-27 08:28 UTC, shahednasser approved these changes
LGTM 🚀

2023-03-27 08:29 UTC, merged