docs: Add upgrade guide for Meilisearch plugin
medusajs/medusa pull request #3583
Opened 2023-03-25 17:30 UTC by olivermrbl

Closed DOCS-668

2023-03-25 17:30 UTC, olivermrbl commented
Exact version still to be decided. Please keep as draft until then :)

2023-03-27 07:38 UTC, shahednasser requested changes
Left some suggestions for fixes. Can you also run `yarn lint:docs --fix` in the root directory of the monorepo to fix eslint errors?

2023-03-27 07:38 UTC, shahednasser commented on docs/content/upgrade-guides/plugins/meilisearch/1-0-0.md
> +Version 1.0.0 of our official Meilisearch plugin comes with breaking changes to the plugin options that are passed to the Meilisearch service through `medusa-config.js`.
```suggestion
Version 1.0.0 of the official Meilisearch plugin comes with breaking changes to the plugin options that are passed to the Meilisearch service through `medusa-config.js`.
```

2023-03-27 07:38 UTC, shahednasser commented on docs/content/upgrade-guides/plugins/meilisearch/1-0-0.md
> +```
As we have ESLint configured on languages like `js`, `jsx`, `ts`, and `tsx`, this block produces errors related to JavaScript. I suggest that we change the block to the following:

~~~suggestion
```js title=medusa-config.js
const plugins = [
  // ...
  {
    config: {
      host,
      apiKey
    }
    settings: {
      indexName: {
        indexSettings: {
          searchableAttributes,
          displayedAttributes
          // ...
        }
        transformer?: (product) => ({
          id: product.id,
          // ...
        })
      }
    }
  }
]
```
~~~

And then we can link to the MeiliSearch plugin for more details on what each of these mean, although I don't think that's necessary considering you already cover it later in the upgrade guide.

2023-03-27 07:38 UTC, shahednasser commented on docs/content/upgrade-guides/plugins/meilisearch/1-0-0.md
> +As you can see from the new object shape, the property `indexSettings` has been introduced to hold the settings specific to Meilisearch’s index options. This has been done to make space for the `tran
```suggestion
As you can see from the new object shape, the property `indexSettings` has been introduced to hold the settings specific to Meilisearch’s index options. This has been done to make space for new settings like `transformer` and `primaryKey`. 
```

2023-03-27 07:38 UTC, shahednasser commented on docs/content/upgrade-guides/plugins/meilisearch/1-0-0.md
> +Previously, you might have configured the Meilisearch plugin as seen below:
```suggestion
Previously, your Meilisearch plugin configurations were something like this:
```

2023-03-27 07:38 UTC, shahednasser commented on docs/content/upgrade-guides/plugins/meilisearch/1-0-0.md
> +```
~~~suggestion
```js title=medusa-config.js
const plugins = [
  // ...
  {
    config: {
      host: "https://search-api-example.com",
      apiKey: "some_key",
    },
    settings: {
      products: {
        searchableAttributes: ["title", "description"],
        attributesToRetrieve: ["title", "description"],
      }
    }
  }
]
```
~~~

2023-03-27 07:38 UTC, shahednasser commented on docs/content/upgrade-guides/plugins/meilisearch/1-0-0.md
> +In the above example, an index `products` has been configured with two options. Updating to 1.0.0 requires you to nest these within the `indexSettings`.
```suggestion
In the above example, an index `products` has been configured with the two options `searchableAttributes` and `attributesToRetrieve`. Updating to 1.0.0 requires you to nest these options within the `indexSettings`. 
```

2023-03-27 07:38 UTC, shahednasser commented on docs/content/upgrade-guides/plugins/meilisearch/1-0-0.md
> +```
~~~suggestion
```js
const plugins = [
  // ...
  {
    config: {
      host: "https://search-api-example.com",
      apiKey: "some_key",
    },
    settings: {
      products: {
        indexSettings: {
          searchableAttributes: ["title", "description"],
          attributesToRetrieve: ["title", "description"],	
        }
      }
    }
  }
]
```
~~~

2023-03-27 07:38 UTC, shahednasser commented on docs/content/upgrade-guides/plugins/meilisearch/1-0-0.md
> +You can read more about the new plugin options properties in the package README.
```suggestion
You can learn more about the new settings in the [MeiliSearch plugin documentation](../../../plugins/search/meilisearch.md)
```

2023-03-27 08:27 UTC, shahednasser approved these changes
LGTM! Thanks a lot for your work @olivermrbl 🚀

2023-03-27 08:27 UTC, merged