docs: added extend documentation pages
medusajs/medusa pull request #3638
Opened 2023-03-30 09:38 UTC by shahednasser

- Added extend entity page
- Added extend repository page
- Added extend service page
- Added details about service lifetime in the Create Service documentation.
- Other small changes across pages.

Closes DOCS-661, DOCS-663, and DOCS-641

2023-03-30 12:08 UTC, adrien2p requested changes

2023-03-30 12:08 UTC, adrien2p commented on docs/content/development/fundamentals/dependency-injection.md
> +By default, it's `TRANSIENT` unless defined differently within the fulfillemnt provider service.
todo: singleton

2023-03-30 12:08 UTC, adrien2p commented on docs/content/development/fundamentals/dependency-injection.md
> +\-
todo: trensient

2023-03-30 12:09 UTC, adrien2p requested changes

2023-03-30 12:09 UTC, adrien2p commented on docs/content/development/endpoints/add-middleware.md
> +Notice that the `LIFE_TIME` property has been set to `Lifetime.SCOPED`. If you want to access new registrations in the dependency container within a service, you must set the lifetime of the service
todo: only valid for core services since the custom services are transient by default

2023-03-30 12:10 UTC, shahednasser commented on docs/content/development/fundamentals/dependency-injection.md
> +\-
I think you mean that each item in the array is transient right? I was thinking of highlighting that too. I'll add it in other places as well

2023-03-30 12:15 UTC, shahednasser commented on docs/content/development/fundamentals/dependency-injection.md
> +By default, it's `TRANSIENT` unless defined differently within the notification provider service.
According to [this](https://github.com/medusajs/medusa/blob/ebd6ab12c944d517f46aede9775d5937e7726962/packages/medusa/src/loaders/plugins.ts#L416) it's Transient, or am I checking the wrong place? 😅

2023-03-31 07:23 UTC, adrien2p approved these changes
LGTM

2023-03-31 07:26 UTC, merged