feat(medusa): Improve prices flow
medusajs/medusa pull request #3703
Opened 2023-04-04 10:39 UTC by adrien2p

FIXES CORE-1304

2023-04-13 09:56 UTC, adrien2p commented on packages/medusa/src/strategies/__tests__/price-selection.js
> -  [
self-review: Those test are never called in develop and the error does not exists

2023-04-14 14:02 UTC, adrien2p commented
Last thing to do is to cleanup everything :)

2023-05-09 15:32 UTC, dwene commented
Looks like some great performance enhancements! We're excited for this one!

2023-05-10 07:30 UTC, olivermrbl requested changes
This is a strong piece of work @adrien2p 🏎️ 

I would love to see the effect of these changes. Any chance we could include that in the PR, if it's not too much work?

2023-05-10 07:30 UTC, olivermrbl commented on packages/medusa/src/migrations/1679950645254-product-domain-impoved-indexes.ts
> +      /* You can turn of this settings if you are in a context with lots of variants) set enable_nestloop to off; */
note-to-self: Add note in upgrade guide

2023-05-10 07:30 UTC, olivermrbl commented on packages/medusa/src/migrations/1679950645254-product-search-gin-indexes.ts
> +      console.warn("Could not create pg_trgm extension or indexes, skipping. If you want to use the pg_trgm extension, please install it manually and then run the migration productSearchGinIndexes167
note-to-self: Add note (+ guide) in documentation

2023-05-10 07:30 UTC, olivermrbl commented on packages/medusa/src/strategies/price-selection.ts
> +    data: {
note-to-self: Breaking change

2023-05-10 07:30 UTC, olivermrbl commented on packages/medusa/src/strategies/price-selection.ts
> +    data: {
note-to-self: Breaking change

2023-05-10 07:30 UTC, olivermrbl commented on packages/medusa/src/strategies/price-selection.ts
> +    data: {
note-to-self: Breaking change

2023-05-10 07:30 UTC, olivermrbl commented on packages/medusa/src/strategies/price-selection.ts
> +    context: PriceSelectionContext & { quantity?: number }
thought: Should we extend the `PriceSelectionContext` instead?

2023-05-10 07:30 UTC, olivermrbl commented on packages/medusa/src/services/pricing.ts
> +    data: {
note-to-self: Breaking change

2023-05-10 07:30 UTC, olivermrbl commented on packages/medusa/src/services/pricing.ts
> +    ).get(variant.id)!
suggestion(non-blocking): I find this rather hard to read
```suggestion
    const singleVariantPricingMap = await this.getProductVariantPricing_(
        [
          {
            variantId: variant.id,
            quantity: pricingContext.price_selection.quantity,
          },
        ],
        pricingContext
      )
    return singleVariantPricingMap.get(variant.id)!
```

2023-05-10 07:30 UTC, olivermrbl commented on packages/medusa/src/services/pricing.ts
> +      productRates = (
thought(this-file, non-blocking): This goes along with my other comment. I generally think we should be explicit about functions that return maps i.e. define a const with a name that reflects it. And then subsequently use the `.get( ... )` to fetch what we want. Wdyt?

2023-05-10 07:30 UTC, olivermrbl commented on packages/medusa/src/services/pricing.ts
> +    const variantsPricingMap = await this.getProductVariantPricing_(
Like we do here

2023-05-10 07:30 UTC, olivermrbl commented on packages/medusa/src/services/pricing.ts
> +    return (
see other comment

2023-05-10 07:30 UTC, olivermrbl commented on packages/medusa/src/services/pricing.ts
> +      await this.getProductPricing_([{ productId, variants }], pricingContext)
see other comment

2023-05-10 07:30 UTC, olivermrbl commented on packages/medusa/src/interfaces/price-selection-strategy.ts
>  import { MoneyAmount } from "../models"
note-to-self: Breaking change

2023-05-10 07:30 UTC, olivermrbl requested changes
This is a strong piece of work @adrien2p 🏎️ 

I would love to see the effect of these changes. Any chance we could include that in the PR, if it's not too much work?

2023-05-15 10:13 UTC, adrien2p commented
> This is a strong piece of work @adrien2p 🏎️
> 
> I would love to see the effect of these changes. Any chance we could include that in the PR, if it's not too much work?

@olivermrbl I can definately re do some perf load testing and share the screen shot

2023-05-15 10:32 UTC, adrien2p commented
With the same load configuration, the perf are two times better overall @olivermrbl. This test is with each product having 50 variants and 2 prices so the requests are fetching 600 variants and 1200 prices. I expect to be better with the current product repo refactoring we are doing

<img width="1746" alt="after_price_list" src="https://github.com/medusajs/medusa/assets/25098370/02256b64-7bd7-43a2-b276-b7d407180a34">
<img width="1826" alt="before_price_list" src="https://github.com/medusajs/medusa/assets/25098370/233a71f0-11b6-41a6-b489-0ac0ee0632b7">

2023-05-16 15:43 UTC, olivermrbl commented on packages/medusa/src/services/pricing.ts
> +      quantity?: number
question: Where and how are we using the `quantity` passed here? I can't seem to find a reason as to why we needed to add this and break the API. Looks like we are only using it to create the cache key, but I might be missing something

2023-05-16 15:53 UTC, adrien2p commented on packages/medusa/src/services/pricing.ts
> +      quantity?: number
The idea was that you can pass different quantities per variant and not necessarily the same quantity for all variants. Otherwise, we can't bulk and we would have to do a call per quantity as a group by quantity. If that's not clear we can huddle to discuss it

2023-05-18 06:28 UTC, olivermrbl approved these changes
LGTM!

2023-05-18 06:55 UTC, merged