chore(medusa): rename buildLegacyFieldsListFrom to objectToStringPath
medusajs/medusa pull request #3738
Opened 2023-04-05 15:40 UTC by riqwan

2023-04-05 15:48 UTC, adrien2p approved these changes
LGTM, should we rename the other to stringPathToObject or keep it as it?

2023-04-05 16:36 UTC, olivermrbl requested changes

2023-04-05 16:36 UTC, olivermrbl commented on packages/medusa/src/repositories/customer-group.ts
> +import { objectToStringPath } from "../utils"
todo: Import from `@medusajs/utils`

2023-04-05 16:36 UTC, olivermrbl commented on packages/medusa/src/repositories/order.ts
> +import { objectToStringPath } from "../utils"
todo: Import from `@medusajs/utils`

2023-04-05 16:36 UTC, olivermrbl commented on packages/medusa/src/repositories/product-category.ts
> +import { objectToStringPath } from "../utils"
todo: Import from `@medusajs/utils`

2023-04-05 16:36 UTC, olivermrbl commented on packages/medusa/src/repositories/product.ts
> +  objectToStringPath,
todo: Import from `@medusajs/utils`

2023-04-05 16:36 UTC, olivermrbl commented on packages/medusa/src/repositories/tax-rate.ts
> +import { objectToStringPath } from "../utils"
todo: Import from `@medusajs/utils`

2023-04-05 16:36 UTC, olivermrbl commented on packages/medusa/src/utils/build-query.ts
> +export function objectToStringPath<TEntity>(
suggestion: Keep this and deprecate it to stay backward compatible. And change all occurrences to import from `@medusajs/utils`

2023-04-07 08:27 UTC, olivermrbl approved these changes
LGTM!

2023-04-07 08:27 UTC, merged