Upgrade medusa-file-s3 and medusa-file-minio to typescript
medusajs/medusa pull request #3740
Opened 2023-04-05 18:16 UTC by dwene

I'm working on a custom CSV import where I need to import images via url and save them in my datastore. Part of that required work done in this PR that hasn't been merged yet. 

https://github.com/medusajs/medusa/pull/2631

I decided to upgrade these to typescript to help eliminate other type bugs that were present.

The biggest change I needed was the `contentType` changes. I've already published my own versions of these changes, so feel free to take this PR or leave it!

2023-04-10 07:42 UTC, olivermrbl approved these changes
LGTM. This contribution is much appreciated @dwene - thanks!

2023-04-10 14:21 UTC, dwene commented on packages/medusa-file-minio/package.json
> +    "@types/stripe": "^8.0.417",
Bad copy paste 😬 . I'll remove it!

2023-04-13 06:48 UTC, olivermrbl reviewed
@adrien2p – do you have any comments before we merge?

Appreciate the contribution @dwene :)

2023-04-13 08:51 UTC, adrien2p commented
> @adrien2p – do you have any comments before we merge?
> 
> Appreciate the contribution @dwene :)

I ll have a look ☺️

2023-04-13 09:45 UTC, adrien2p requested changes

2023-04-13 09:45 UTC, adrien2p commented on packages/medusa-file-minio/src/services/minio.ts
> +  private bucket_: string
todo: Make them protected so that if anybody want to add custom methods by extending this service they will have access to those props

2023-04-13 09:45 UTC, adrien2p commented on packages/medusa-file-minio/src/services/minio.ts
> +  private buildUrl(bucket: string, key: string) {
todo: protected

2023-04-13 09:45 UTC, adrien2p commented on packages/medusa-file-minio/src/services/minio.ts
>      return this.uploadFile(file)
todo: return await

2023-04-13 09:45 UTC, adrien2p commented on packages/medusa-file-minio/src/services/minio.ts
>      return this.uploadFile(file, { isProtected: true })
todo: return await

2023-04-13 09:45 UTC, adrien2p commented on packages/medusa-file-minio/src/services/minio.ts
> +    const usePrivateBucket: boolean = fileData.usePrivateBucket ?? false
todo:    ` const usePrivateBucket = !!fileData.usePrivateBucket`

2023-04-13 09:45 UTC, adrien2p commented on packages/medusa-file-minio/src/services/minio.ts
> +    const usePrivateBucket: boolean = !!fileData.usePrivateBucket
todo: rm boolean

2023-04-13 09:45 UTC, adrien2p commented on packages/medusa-file-minio/src/services/minio.ts
> +  private getClient(
todo: protected

2023-04-13 09:45 UTC, adrien2p commented on packages/medusa-file-s3/src/services/s3.ts
> +  private bucket_: string
todo: update all visibility according to the same comments in the minio plugin

2023-04-13 09:45 UTC, adrien2p commented on packages/medusa-file-s3/src/services/s3.ts
> +  private getClient = (overwriteConfig: Partial<ClientConfiguration> = {}) => {
todo: Move to a method instead of assigning to a property

2023-04-13 09:45 UTC, adrien2p commented on packages/medusa-file-s3/src/services/s3.ts
> +    return this.uploadFile(file)
todo: return await

2023-04-13 09:45 UTC, adrien2p commented on packages/medusa-file-s3/src/services/s3.ts
> +    return this.uploadFile(file, { acl: "private" })
todo: return await

2023-04-16 07:42 UTC, olivermrbl commented
@dwene – Would you have time to attend to these requested changes? If not, let me know, and we can dedicate resources to getting this one across the line.

2023-04-17 17:00 UTC, dwene commented
@olivermrbl @adrien2p addressed!

2023-04-19 06:43 UTC, olivermrbl commented
/snapshot-this

2023-04-19 06:44 UTC, olivermrbl commented
> /snapshot-this is not supported on pull requests from forked repositories.

damn 😢 

will run local tests instead :)

2023-04-23 10:31 UTC, merged