fix(medusa-payment-stripe): Catch on idempotency key retrieve if not found
medusajs/medusa pull request #4025
Opened 2023-05-05 10:52 UTC by adrien2p

**What**
In case the idempotency key is not found, an error will be thrown. We actually want to catch this error and create the key if it does not exists

2023-05-05 14:27 UTC, olivermrbl requested changes

2023-05-05 14:27 UTC, olivermrbl commented on packages/medusa-payment-stripe/src/api/utils/__tests__/utils.spec.ts
> +        it.only("should complete the cart on non existing order", async () => {
```suggestion
        it("should complete the cart on non existing order", async () => {
```

2023-05-05 14:27 UTC, olivermrbl commented on packages/medusa-payment-stripe/src/api/utils/__tests__/utils.spec.ts
> +      it.only("should complete the cart on non existing order", async () => {
```suggestion
      it("should complete the cart on non existing order", async () => {
```

2023-05-05 14:29 UTC, olivermrbl approved these changes
LGTM

2023-05-05 14:54 UTC, merged

2023-05-10 10:02 UTC, pepijn-vanvlaanderen commented
@adrien2p we came accross this issue as well, your PR fixes the retrieval when no idempotency key exists, however there is also a missing withTransaction in the `capturePaymentIfNecessary` function, resulting in no order found when it is just created before. Also see this PR of my co-worker: https://github.com/medusajs/medusa/pull/3930/files#diff-a690d99fec6c0969d14e9ff67236a1ee53e1b694f4bac7e3b22bb7a51aca638c