feat: Allow backorder on swaps
medusajs/medusa pull request #404
Opened 2021-09-16 13:08 UTC by olivermrbl

**What**
- Allowing backorder on swaps. We can create swaps with items, that are out of stock.
- Adds a prop, `payment_authorized_at` on carts indicating when payment was authorized. Previously we used `completed_at` but this is not really appropriate since an authorized payment does not necessarily mean, that a cart is completed.

**Why**
It was requested from customers to allow for swap creation even though items was out of stock. This is only doable from an admin point of view. Storefront swaps always require inventory for the items in question.

**Testing**
- fails to complete swap cart with items inventory not/partially covered
- successfully completes swap cart with items inventory not/partially covered due to backorder flag

2021-09-16 13:08 UTC, olivermrbl commented on integration-tests/api/__tests__/admin/swaps.js
> +const orderSeeder = require("../../helpers/order-seeder")
Only formatting changes to this file :)

2021-09-16 13:09 UTC, olivermrbl commented on integration-tests/api/helpers/cart-seeder.js
>      type: "default",
Only formatting and extra seed data.

2021-09-16 13:09 UTC, olivermrbl commented on integration-tests/api/helpers/swap-seeder.js
>      id: "order-with-swap",
Only formatting changes.

2021-09-16 13:11 UTC, olivermrbl commented on packages/medusa/src/api/routes/admin/orders/create-swap.js
> + *             description: If true, swaps can be completed with items out of stock
As default, we allow backorder on swaps made from an admin point of view

2021-09-16 13:12 UTC, olivermrbl commented on packages/medusa/src/api/routes/store/carts/complete-cart.js
Added a try-catch to return proper error on insufficient inventory

2021-09-16 13:13 UTC, olivermrbl commented on packages/medusa/src/models/swap.ts
> +
Generally, we don't want to allow backorder on swaps, hence why we default to `false`

2021-09-16 13:14 UTC, olivermrbl commented on packages/medusa/src/services/cart.js
At this point in time the cart os not really completed, which is why we added the new flag.

2021-09-16 13:14 UTC, olivermrbl commented on packages/medusa/src/services/cart.js
>        }
Same as above.

2021-09-16 13:14 UTC, olivermrbl commented on packages/medusa/src/services/order.js
> +
As a final step in cart completion, we set the proper flag.

2021-09-16 13:16 UTC, olivermrbl commented on packages/medusa/src/services/order.js
> +            .update(cart.id, { payment_authorized_at: null })
In case we cancel the payment, we should also cancel the payment authorization on the cart.

2021-09-18 13:20 UTC, srindom requested changes
Nice 🚀

2021-09-18 13:20 UTC, srindom commented on packages/medusa/src/migrations/1630505790603-allow_backorder_swaps.ts
> +        await queryRunner.query(`ALTER TYPE "public"."swap_payment_status_enum" RENAME TO "swap_payment_status_enum_old"`);
rm `"public"`

2021-09-18 13:20 UTC, srindom commented on packages/medusa/src/services/payment-provider.js
> +      return pay
Maybe `return await paymentRepo.save(payment)` would be nicer

2021-09-19 13:16 UTC, srindom approved these changes

2021-09-19 13:33 UTC, merged