chore(utils): clean util package deps
medusajs/medusa pull request #4146
Opened 2023-05-22 09:33 UTC by fPolic

**WIP**

1. removed `class-validator`
    - replace `isEmail` function
2. removed `class-transformer`
3. removed `typeorm`
    - removed `transaction-base-service` and replace usage of this with a local class from `../interface`
    - removed `build-query`replace usage in the stock and inventory modules with a local utils file
    - [TODO] remove `db-aware-column`
    - [TODO] remove `base-entity`
    - [TODO] remove `soft-deletable-entity`

2023-05-22 10:23 UTC, adrien2p requested changes

2023-05-22 10:23 UTC, adrien2p commented on packages/stock-location/src/utils/build-query.ts
> +import { ExtendedFindConfig, FindConfig } from "@medusajs/types"
todo: The buildquery from utils wasn't align with the one in medusa, I ve updated that [here](https://github.com/medusajs/medusa/pull/4148), you can have a look to apply the changes in buildWhere

2023-05-22 10:23 UTC, adrien2p commented on packages/inventory/src/utils/build-query.ts
>   * Used to build TypeORM queries.
same as the other comment

2023-05-22 10:23 UTC, adrien2p commented on packages/utils/src/common/is-email.ts
> +function isEmail(email: string) {
todo: add unit tests

2023-05-22 10:23 UTC, adrien2p commented on packages/utils/src/common/object-to-string-path.ts
> +    | FindOptionsRelations<TEntity> = {}
todo: Rm typeorm types and replace by `unknown`

2023-05-22 10:23 UTC, adrien2p commented on packages/utils/src/common/object-to-string-path.ts
> +): (keyof TEntity)[] {
todo: replace by string[] as it does return more than `(keyof TEntity)[]` since it can be sub relations/fields etc

2023-05-22 10:23 UTC, adrien2p commented on packages/utils/src/common/object-to-string-path.ts
> +  if (!Object.keys(input).length) {
todo: add check `isObject`

2023-05-22 10:24 UTC, adrien2p commented on packages/utils/src/common/object-to-string-path.ts
> +  return Array.from(output) as (keyof TEntity)[]
todo: remove cast based on previous comment

2023-05-22 10:24 UTC, adrien2p commented on packages/utils/src/common/object-to-string-path.ts
> +export function objectToStringPath<TEntity>(
todo: rm `<Tentity>`

2023-05-22 10:24 UTC, adrien2p commented on packages/inventory/src/utils/query.ts
> +import { buildQuery, objectToStringPath } from "./build-query"
todo: After the changes I ve proposed, you can use the one from the utils package

2023-05-22 10:25 UTC, adrien2p commented on packages/stock-location/src/utils/db-aware-column.ts
> +import { Column, ColumnOptions, ColumnType } from "typeorm"
todo: we don't support SQlite anymore so I think we can compately remove this file and usage

2023-05-23 10:53 UTC, olivermrbl approved these changes
Great cleanup! 

Not happy about having duplicate util functions, but I guess this is the best solution as we migrate away from `typeorm`. We'll just have to be aware that changes to the `build-query` are always reflected across all it's definitions.

Pending @adrien2p's approval :)

2023-05-25 18:50 UTC, olivermrbl commented
@adrien2p any final remarks?

2023-05-26 07:17 UTC, adrien2p commented
on it @olivermrbl

2023-05-26 08:10 UTC, adrien2p commented
@olivermrbl @carlos-r-l-rodrigues @fPolic I ve pushed a commit that clean up a bit the build-query utils, what I ve done is the following
- Utils
  - Re-add the build-query utility with methods that can be reused in the modules and medusa to avoid too many places to change if needed and centralize common behavior where the dependency to Typeform can be avoided
- stock-location and inventory
  - Remove unused methods and reuse common utils from the utils package
  - Cleanup the usage of the FindOperator to simplify addition/removal/update of the find operator usage and make it easier to maintain
- medusa
  - Remove unused methods and reuse common utils from the utils package
  - Cleanup the usage of the FindOperator to simplify addition/removal/update of the find operator usage and make it easier to maintain

The main idea was to keep what can be common in the utils package and just move the specifics stuff to the different modules and to medusa. Also, in case we need to change the build-query utils I wanted to make it easier to have less maintenance in case of changes and simplify the addition/removal/update of support for other Operator as it happens recently

2023-05-26 08:37 UTC, carlos-r-l-rodrigues approved these changes
LGTM

2023-05-26 10:17 UTC, olivermrbl approved these changes
LGTM! 💪

2023-05-26 11:20 UTC, merged