Feat/nested return reasons
medusajs/medusa pull request #418
Opened 2021-09-24 08:52 UTC by pKorsholm

**What**
- Add support for nested return reasons
- Add soft deletion method to return reasons

**How**
- By using existing patterns
- By querying only return reasons without a category and adding a children relation to support hierarchal results

**Testing**
-  integration testing
  - creation of nested return reasons
  - list return reasons from the parent category without children
  - failing to create a doubly nested return reason

2021-09-24 10:46 UTC, olivermrbl commented on packages/medusa/src/models/return-reason.ts
> +    { cascade: ["insert"] }
Should have cascade `delete` as well, such that if we choose to delete a parent return reason, all children are deleted.

2021-09-24 10:57 UTC, srindom requested changes
Please add the following integration tests:
- list storefront return reasons
  - should return nested reasons
- adding a return reason to a return line item
  - test that it only works with "leaf" reasons

2021-09-24 10:57 UTC, srindom commented on packages/medusa/src/api/routes/admin/return-reasons/delete-reason.js
> + * @oas [delete] /returnReason/{id}
should be `/return-reasons/{id}`

2021-09-24 10:57 UTC, srindom commented on integration-tests/api/__tests__/admin/return-reason.js
> +      console.log(nested_response.data.return_reasons)
rm

2021-09-24 11:08 UTC, olivermrbl commented on packages/medusa/src/models/return-reason.ts
> +  @JoinColumn({ name: "parent_return_reason_id" })
Add an integration, that validates this, since Typeorm seems to be a bit tricky when it comes to cascading.

2021-09-24 11:08 UTC, olivermrbl commented on packages/medusa/src/models/return-reason.ts
> +  @JoinColumn({ name: "parent_return_reason_id" })
Also since this is a parent entity of same type, it might not play out :) But would be great to get confirmed.

2021-09-24 11:38 UTC, pKorsholm commented on packages/medusa/src/api/routes/admin/return-reasons/delete-reason.js
> + * @oas [delete] /returnReason/{id}
done

2021-09-24 11:38 UTC, pKorsholm commented on integration-tests/api/__tests__/admin/return-reason.js
> +      console.log(nested_response.data.return_reasons)
done

2021-09-27 13:22 UTC, pKorsholm commented on packages/medusa/src/models/return-reason.ts
> +    { cascade: ["insert"] }
added it on both sides of the relation as well as added the relation to the deletion query in the return reason service

2021-09-27 16:24 UTC, srindom requested changes

2021-09-27 16:24 UTC, srindom commented on integration-tests/api/__tests__/store/returns.js
> +          console.log(err.response)
remove

2021-09-27 16:24 UTC, srindom commented on packages/medusa/src/services/return-reason.js
> +      if (!reason) return Promise.resolve()
Must be wrapped in `{}` block

2021-09-27 16:24 UTC, srindom commented on packages/medusa/src/services/return-reason.js
> +      const reason = await this.retrieve(returnReasonId, {relations: ["return_reason_children"]})
Please check that your linter/prettier is correctly configured. This line is more than 80 cols wide so it should be split into multiple lines

2021-09-27 16:24 UTC, srindom commented on packages/medusa/src/services/return-reason.js
> +  }
I don't think that this is necessary. Use this instead

```javascript
const returnReasons = await returnReasonService.list({ id: [id1, id2,....] })
```

2021-09-27 16:24 UTC, srindom commented on packages/medusa/src/services/return.js
> +      const returnReasons = await this.returnReasonService_.listReasonsFromIds(returnLines.map(rl => rl.reason_id))
See above change regarding `list({ id: idArray })`. 

Also this line is too wide.

2021-09-27 16:35 UTC, srindom requested changes

2021-09-27 16:35 UTC, srindom commented on integration-tests/api/__tests__/admin/return-reason.js
> +
rm

2021-09-27 16:35 UTC, srindom commented on integration-tests/api/__tests__/admin/return-reason.js
> +      expect(deleteResult.data).toEqual({id: response.data.return_reason.id, object: 'return_reason', deleted: true})
too wide - please insure that you have a prettier plugin installed in your editor.

2021-09-27 16:35 UTC, srindom commented on integration-tests/api/__tests__/admin/return-reason.js
> +
rm

2021-09-27 16:35 UTC, srindom commented on integration-tests/api/__tests__/admin/return-reason.js
> +    it('deletes cascade through nested return reasons', async () => {expect.assertions(10)
should be two lines

2021-09-27 16:35 UTC, srindom commented on integration-tests/api/__tests__/store/return-reason.js
>        expect(response.data.return_reasons).toEqual([
Can you use a snapshot test here instead

2021-09-29 07:03 UTC, srindom approved these changes

2021-09-29 07:22 UTC, merged