fix(admin-ui): Bundle admin commands
medusajs/medusa pull request #4193
Opened 2023-05-29 10:18 UTC by kasperkristensen

WIP

2023-05-29 10:18 UTC, kasperkristensen commented
/snapshot-this

2023-05-29 10:42 UTC, kasperkristensen commented
/snapshot-this

2023-05-29 10:55 UTC, kasperkristensen commented
/snapshot-this

2023-05-29 11:16 UTC, kasperkristensen commented
/snapshot-this

2023-05-29 11:49 UTC, kasperkristensen commented
/snapshot-this

2023-05-29 12:06 UTC, kasperkristensen commented
/snapshot-this

2023-05-30 10:44 UTC, adrien2p approved these changes
LGTM, just small questions

2023-05-30 10:44 UTC, adrien2p commented on packages/ui/tailwind.content.js
> +    "../../../clean/my-medusa-store/dist/admin//**/*.{js,ts,jsx,tsx}",
question: what is my-medusa-store? in that context?

2023-05-30 10:44 UTC, adrien2p commented on packages/admin-ui/tsconfig.json
> +  "include": ["src", "../vite.config.dev.ts", "../tsup.config.ts"],
question: Since the root dir is src and we are including other files from the parent, will the dist  looks like
- dist
  - src
  - vite
  - tsup

2023-05-30 10:53 UTC, kasperkristensen commented
Sorry @adrien2p forgot to set it as a draft, no need to review this right now, was testing out if I could fix using Vite for the dev command

2023-05-30 10:54 UTC, adrien2p commented
> Sorry @adrien2p forgot to set it as a draft, no need to review this right now, was testing out if I could fix using Vite for the dev command

ahah my bad, sorry @kasperkristensen

2023-06-06 08:33 UTC, kasperkristensen commented
/snapshot-this

2023-06-06 08:45 UTC, kasperkristensen commented
/snapshot-this

2023-06-12 14:00 UTC, kasperkristensen commented
/snapshot-this

2023-06-13 08:30 UTC, kasperkristensen commented
/snapshot-this

2023-06-13 08:40 UTC, olivermrbl requested changes
lets gooooo! insane piece of work @kasperkristensen 🚀 🚀 

minor things ... also, let's remove the changesets for the admin packages and figure out a beta release path for those

2023-06-13 08:40 UTC, olivermrbl commented on packages/admin-ui/src/node/actions/clean.ts
> +  console.log("Cleaning cache directory", cacheDir)
question: This meant to be here?

2023-06-13 08:40 UTC, olivermrbl commented on packages/admin-ui/src/node/webpack/get-custom-webpack-config.ts
> +      console.log(JSON.stringify(config, null, 2))
```suggestion
```

2023-06-13 08:40 UTC, olivermrbl commented on packages/admin-ui/ui/src/domain/collections/details/index.tsx
> +                injectionZone="product_collection.details.after"
thought: Should this not be `before`?
```suggestion
          {getWidgets("product_collection.details.before").map((w, i) => {
            return (
              <WidgetContainer
                key={i}
                entity={collection}
                injectionZone="product_collection.details.before"
```

2023-06-13 09:16 UTC, kasperkristensen commented
> lets gooooo! insane piece of work @kasperkristensen 🚀 🚀
> 
> minor things ... also, let's remove the changesets for the admin packages and figure out a beta release path for those

Yea let's remove all the changesets, but let us wait until we have merged this into the feature branch, as creating snapshots gets a little weird when their are no changesets for the packages 💪

2023-06-13 09:16 UTC, kasperkristensen commented
/snapshot-this

2023-06-13 09:41 UTC, kasperkristensen commented
/snapshot-this

2023-06-13 09:51 UTC, kasperkristensen commented
/snapshot-this

2023-06-13 09:52 UTC, kasperkristensen commented
/snapshot-this

2023-06-13 10:15 UTC, kasperkristensen commented
/snapshot-this

2023-06-13 15:16 UTC, merged