fix(medusa): Order edit missing transaction when consuming the inventory module
medusajs/medusa pull request #4211
Opened 2023-05-30 13:38 UTC by adrien2p

2023-05-30 19:13 UTC, pKorsholm approved these changes
LGTM!

2023-05-30 19:13 UTC, pKorsholm approved these changes
LGTM!

2023-05-30 19:19 UTC, olivermrbl requested changes
Do we not need to update [`InventoryService.deleteReservationItemsByLineItem`](https://github.com/medusajs/medusa/blob/a98703ce460120cd437369f926ff7d4e16073e2a/packages/inventory/src/services/inventory.ts#L443) too?

2023-05-30 19:35 UTC, adrien2p commented
> Do we not need to update [`InventoryService.deleteReservationItemsByLineItem`](https://github.com/medusajs/medusa/blob/a98703ce460120cd437369f926ff7d4e16073e2a/packages/inventory/src/services/inventory.ts#L443) too?

Gosh I was sure to have done it, i didn't got any issues locally during my test and it slipped through my fingers, nice catch 🫣

2023-05-30 19:38 UTC, adrien2p commented on packages/medusa/src/services/product-variant-inventory.ts
> +    await this.inventoryService_.deleteReservationItemsByLineItem(itemIds)
self review: missing context

2023-06-02 08:31 UTC, olivermrbl approved these changes
LGTM

2023-06-05 09:01 UTC, merged