feat(create-medusa-app): update command for a better onboarding experience
medusajs/medusa pull request #4215
Opened 2023-05-30 15:52 UTC by shahednasser

## What

Updates the NPX `create-medusa-app` command for a better user and onboarding experience.

## Testing

- change to the `packages/create-medusa-app` directory
- install dependencies if necessary
- run `yarn dev`

2023-05-30 15:53 UTC, shahednasser commented
/snapshot-this

2023-05-30 16:43 UTC, shahednasser commented
/snapshot-this

2023-05-30 16:58 UTC, shahednasser commented
/snapshot-this

2023-06-02 10:27 UTC, shahednasser commented
/snapshot-this

2023-06-05 16:10 UTC, shahednasser commented
/snapshot-this

2023-06-06 13:10 UTC, shahednasser commented
/snapshot-this

2023-06-06 14:23 UTC, shahednasser commented
/snapshot-this

2023-06-06 15:04 UTC, shahednasser commented
/snapshot-this

2023-06-06 17:07 UTC, olivermrbl requested changes
this is a fantastic addition 🚀 🚀

2023-06-06 17:07 UTC, olivermrbl commented on packages/create-medusa-app/src/utils/prepare-project.ts
> +    if (!fs.existsSync(path.join(directory, "data", "seed.jsons"))) {
todo: 
```suggestion
    if (!fs.existsSync(path.join(directory, "data", "seed.json"))) {
```

2023-06-06 17:07 UTC, olivermrbl commented on packages/create-medusa-app/src/utils/facts.ts
> +  "You can listen to events to perform asynchornus actions using Subscribers.",
```suggestion
  "You can listen to events to perform asynchronous actions using Subscribers.",
```

2023-06-07 07:25 UTC, shahednasser commented
/snapshot-this

2023-06-07 07:26 UTC, shahednasser commented on packages/create-medusa-app/src/utils/prepare-project.ts
> +    if (!fs.existsSync(path.join(directory, "data", "seed.jsons"))) {
Nice catch 😅

2023-06-07 08:44 UTC, shahednasser commented
/snapshot-this

2023-06-07 09:26 UTC, shahednasser commented
/snapshot-this

2023-06-07 11:58 UTC, olivermrbl approved these changes
LGTM, great work!! 🚢

2023-06-07 18:34 UTC, merged