chore(medusa): Improve database loader error handling
medusajs/medusa pull request #4254
Opened 2023-06-06 08:08 UTC by adrien2p

FIXES CORE-1400

2023-06-06 08:24 UTC, olivermrbl reviewed
Should we place this in `utils` to make it reusable in our modules?

2023-06-06 17:14 UTC, olivermrbl requested changes
love this!

2023-06-06 17:14 UTC, olivermrbl commented on packages/utils/src/common/handle-postgres-database-error.ts
> +import { EOL } from "os"
praise: Very nice!

2023-06-06 17:14 UTC, olivermrbl commented on packages/utils/src/common/handle-postgres-database-error.ts
> +      postgres://user:password@host:post/db_name - If there is no password, you can omit it.
```suggestion
      `Failed to establish a connection to PostgreSQL. Please ensure the following is true and try again:
      - You have a PostgreSQL database running
      - You have passed the correct credentials in medusa-config.js
      - You have formatted the database connection string correctly. See below:
      "postgres://[username]:[password]@[host]:[post]/[db_name]" - If there is no password, you can omit it from the connection string
```

2023-06-06 17:14 UTC, olivermrbl commented on packages/utils/src/common/handle-postgres-database-error.ts
> +      `The specified connection url for your PostgreSQL database might contains illegal characters. Please check that all the connection segments contains only allowed characters [a-zA-Z0-9]${EOL}${e
```suggestion
      `The specified connection string for your PostgreSQL database might have illegal characters. Please check that it only contains allowed characters [a-zA-Z0-9]${EOL}${err.message}`
```

2023-06-07 06:25 UTC, pKorsholm approved these changes
LGTM w/ Oli's changes 😄

2023-06-07 08:22 UTC, olivermrbl commented
Unit tests need updating 👍

2023-06-07 08:57 UTC, merged