[WIP] chore: Use caret range
medusajs/medusa pull request #4276
Opened 2023-06-10 16:08 UTC by olivermrbl

2023-06-12 08:06 UTC, adrien2p requested changes

2023-06-12 08:06 UTC, adrien2p commented on packages/medusa-file-minio/package.json
> +    "@medusajs/medusa": "^1.12.0",
todo: Add to peers

2023-06-12 08:06 UTC, adrien2p commented on packages/medusa-file-s3/package.json
> +    "@medusajs/medusa": "^1.12.0",
todo: add to peers

2023-06-12 08:06 UTC, adrien2p commented on packages/medusa-fulfillment-webshipper/package.json
> +    "@medusajs/medusa": "^1.12.0",
todo: same

2023-06-12 08:06 UTC, adrien2p commented on packages/medusa-payment-klarna/package.json
>      "@babel/plugin-transform-classes": "^7.9.5",
todo: move test utils to dev

2023-06-12 08:06 UTC, adrien2p commented on packages/medusa-plugin-algolia/package.json
> +    "@medusajs/modules-sdk": "^1.8.7",
todo: this plugins should use the types packages instead of the sdk, don't know if we want to include in that pr but it is not mandatory

2023-06-12 08:06 UTC, adrien2p commented on packages/medusa-plugin-contentful/package.json
>      "@babel/plugin-transform-classes": "^7.9.5",
todo: move test utils to dev

2023-06-12 08:06 UTC, adrien2p commented on packages/medusa-plugin-economic/package.json
>      "@babel/plugin-transform-classes": "^7.9.5",
todo: move test utils to dev

2023-06-12 08:06 UTC, adrien2p commented on packages/medusa-plugin-meilisearch/package.json
> +    "@medusajs/medusa": "^1.12.0",
todo: missing peers

2023-06-12 08:06 UTC, adrien2p commented on packages/medusa-plugin-restock-notification/package.json
> +    "medusa-interfaces": "^1.3.7"
todo: missing dev deps

2023-06-12 08:06 UTC, adrien2p commented on packages/medusa-plugin-segment/package.json
>      "analytics-node": "^3.4.0-beta.1",
todo: move test utils

2023-06-12 08:06 UTC, adrien2p commented on packages/medusa-plugin-sendgrid/package.json
>      "@babel/plugin-transform-classes": "^7.9.5",
todo: move test utils to dev

2023-06-12 08:06 UTC, adrien2p commented on packages/medusa-plugin-slack-notification/package.json
>      "@babel/plugin-transform-classes": "^7.9.5",
todo: same as the previous one

2023-06-12 08:06 UTC, adrien2p commented on packages/medusa-plugin-twilio-sms/package.json
>      "@babel/plugin-transform-classes": "^7.9.5",
todo: move test utils to dev

2023-06-12 08:06 UTC, adrien2p commented on packages/medusa-plugin-wishlist/package.json
>      "body-parser": "^1.19.0",
todo: sane as previous

2023-06-12 08:06 UTC, adrien2p commented on packages/medusa-source-shopify/package.json
>    "dependencies": {
todo: move test utils to dev

2023-06-13 07:54 UTC, olivermrbl commented
@adrien2p – this should be ready for a second review :)

2023-06-13 07:54 UTC, adrien2p commented
> @adrien2p – this should be ready for a second review :)

@olivermrbl I was about to start the second review 😂

2023-06-13 08:45 UTC, adrien2p requested changes

2023-06-13 08:45 UTC, adrien2p commented on package.json
> +      "packages/medusa-react",
question: shouldn't `package/*` include them?

2023-06-13 08:45 UTC, adrien2p commented on packages/medusa-file-s3/package.json
> +    "@medusajs/medusa": "^1.12.0",
todo: should be in dev deps

2023-06-13 08:45 UTC, adrien2p commented on packages/medusa-file-spaces/package.json
> +    "medusa-interfaces": "^1.3.7"
todo: Missing carret in the dev deps

2023-06-13 08:45 UTC, adrien2p commented on packages/medusa-payment-paypal/package.json
> +    "@medusajs/medusa": "^1.12.0",
todo: missing carret in the peers

2023-06-13 08:45 UTC, adrien2p commented on packages/medusa-react/package.json
> +    "@medusajs/medusa-js": "^6.0.0",
todo: Since medusa-js is a dependency, it does not have to be in devDeps

2023-06-13 08:45 UTC, adrien2p commented on packages/medusa-source-shopify/package.json
> +    "medusa-interfaces": "^1.3.7"
todo: rm

2023-06-13 08:45 UTC, adrien2p commented on packages/medusa/package.json
>      "@types/lodash": "^4.14.191",
todo: all @types should only be present in devDeps

2023-06-13 17:22 UTC, olivermrbl commented on package.json
> +      "packages/medusa-react",
I am forcing the build order of these three packages, because we've had issues with that in the pipeline. Should have added a comment :D

2023-06-14 12:13 UTC, adrien2p approved these changes
LGTM, sounds good to me

2023-06-14 12:36 UTC, olivermrbl commented
/snapshot-this

2023-06-14 13:18 UTC, merged