Fix/hide password hash
medusajs/medusa pull request #429
Opened 2021-09-28 16:02 UTC by pKorsholm

**What** 
- removed password hashes from results containing users and customers unless explicitly stated

**Why**
- To remove any unnecessary user information

**How**
- using `select: false` in models to remove them from general queries

**Testing** 
- integration tests using snapshots
  - admin/create-session successful creation but no password hash in result
  - store/create-session successful creation but no password hash in result

2021-09-29 06:59 UTC, olivermrbl requested changes
Very cool! Tiny changes :)

2021-09-29 06:59 UTC, olivermrbl commented on packages/medusa/src/services/user.js
> +    const query = this.buildQuery_({ email: email }, config)
Simply do `this.buildQuery_({ email }`

2021-09-29 06:59 UTC, olivermrbl commented on packages/medusa/src/services/auth.js
> +        const customer = await this.customerService_.retrieveByEmail(email, {})
Remove empty object

2021-09-29 06:59 UTC, olivermrbl commented on packages/medusa/src/services/auth.js
> +        const user = await this.userService_.retrieveByEmail(email, {})
Remove empty object

2021-09-29 07:23 UTC, pKorsholm commented
I added email validation to the user service as discussed

2021-09-30 09:12 UTC, srindom requested changes
Quick fixes and we can merge - thanks!

2021-09-30 09:12 UTC, srindom commented on integration-tests/api/__tests__/admin/auth.js
> +describe("/admin/discounts", () => {
`admin/auth`

2021-09-30 09:12 UTC, srindom commented on integration-tests/api/__tests__/store/auth.js
> +describe("/admin/discounts", () => {
`/store/auth`

2021-09-30 09:12 UTC, srindom commented on packages/medusa/src/services/auth.js
> +import UserService from "./user"
rm

2021-09-30 10:17 UTC, srindom approved these changes

2021-09-30 10:18 UTC, srindom approved these changes
Great work!

2021-09-30 10:19 UTC, merged