feat: add rma shipping options
medusajs/medusa pull request #444
Opened 2021-10-01 15:42 UTC by zakariaelas

### What

- Adds support for RMA shipping options on swaps

### Why
- We want to allow customer service to choose between and customize shipping options when creating a swap

### How
**Models**
- adds an `RMAShippingOption` model and repository
- updates `Swap` and `ClaimOrder` models to include an `rma_shipping_options` one-to-many relationship

**Services**
- modifies `SwapService.create` method to include a `rmaShippingOptions` argument used in the creation of a swap
- adds a `CartService.addRMAMethod` responsible for adding the correct shipping method (either from a normal or rma option) to a cart
- tweaks `CartService.addShippingMethod` to include a custom price. This is used in case we need to add a method from a `RMAShippingOption` 
- adds a `ShippingProfileService.fetchRMAOptions`

**API**
- updates `POST /store/carts/:id/shipping-methods/` to use the cart service's `addRMAMethod` instead of `addShippingMethod`. In case the option does not correspond to an RMAShippingOption, then `addRMAMethod` will simply call `addShippingMethod`
- updates `POST /admin/orders/:id/swap` to accept a `rma_shipping_options` list request payload
- updates `GET /store/shipping-options/:cart_id/` to either call `shippingProfileService.fetchRMAOptions` in case `cart.type == swap || claim` or `shippingProfileService.fetchCartOptions` in case the cart is not a swap nor a claim

### Testing
- integration test to ensure the creation of a swap with `rma_shipping_options`
- integration test to ensure the addition of a normal and rma shipping method to a cart
- integration test to ensure the retrieval of shipping options for both a swap and default cart
- unit tests for API changes and new service methods

2021-10-03 10:54 UTC, olivermrbl requested changes
Great! 

But thinking, we might have gone a step too far, too early with the RMA shipping options for claims. Currently, we don't have a clear idea of, how we want to extend the claims functionality with the RMA options (i take the blame for including it in the description in the first place). Therefore, we should perhaps restrict the RMA options to only work for swaps for now. Would love your input on this @srindom.

2021-10-03 10:54 UTC, olivermrbl commented on packages/medusa/src/api/routes/store/shipping-options/list-shipping-options.js
> +      options = await shippingProfileService.fetchCartOptions(cart)
Similar to how we approach adding a shipping method, would it be an idea to move this to the service layer?

2021-10-03 10:54 UTC, olivermrbl commented on packages/medusa/src/migrations/1632851018347-add_rma_shipping_options.ts
> +        await queryRunner.query(`DROP TYPE "public"."cart_type_enum_old"`);
Remove `public.`

2021-10-03 10:54 UTC, olivermrbl commented on packages/medusa/src/migrations/1632851018347-add_rma_shipping_options.ts
> +        await queryRunner.query(`ALTER TYPE "public"."cart_type_enum_old" RENAME TO "cart_type_enum"`);
Remove `public.`

2021-10-04 10:46 UTC, srindom requested changes
A thought that comes to mind looking over this PR and which also addresses the question raised by @olivermrbl:

Should we modify the RMA relations to only belong to Carts i.e. when creating a Swap the resulting RMA options would have:

```
RMA option
- option_id
- price
- cart_id <-- corresponds to swap.cart_id
```

Doing it this way would mean that we wouldn't have to replicate functionality across swaps + claims + potential future entities, as long as these entities can use the Cart API for processing. It would also have the added benefit of giving store operators the option of specifying custom shipping options in relation to Draft Orders.

Given that we agree that this is a good idea we should probably reconsider the naming as RMA options would likely be a too narrow scope (it already is if we allow these to be applied to draft order carts). Maybe something like `Custom Shipping Options` would make sense, but happy to hear suggestions.

Please let me know what you think? :)

2021-10-04 22:31 UTC, zakariaelas commented on packages/medusa/src/services/cart.js
> +  }
love the suggestion! so true!

2021-10-06 17:36 UTC, olivermrbl commented on packages/medusa/src/services/cart.js
> +    ) {
Would prefer `if(cart.custom_shipping_options?.length)`

2021-10-06 17:37 UTC, olivermrbl commented on packages/medusa/src/services/shipping-profile.js
> +    if (customShippingOptions && customShippingOptions.length > 0)
Same as above: `customShippingOptions?.length`

2021-10-06 17:41 UTC, olivermrbl commented on packages/medusa/src/services/shipping-profile.js
> +    if (customShippingOptions && customShippingOptions.length > 0)
And would love brackets :)

2021-10-06 17:42 UTC, olivermrbl commented on packages/medusa/src/services/shipping-profile.js
> +    if (customShippingOptions && customShippingOptions.length > 0)
We could do
```
if (cart.custom_shipping_options?.length) {
    return cart.custom_shipping_options
}
```

2021-10-13 09:54 UTC, zakariaelas commented
@srindom I feel like we might run into some issues given how we implement the “Give free shipping” option. To re-iterate, selecting ‘give free option’ will also set the digital copy and printed copy as shipping options. If there is no way to filter out these, I think it’s good to tell your clients so that it makes sense :slightly_smiling_face:
![image](https://user-images.githubusercontent.com/33696020/137111093-e04353b8-b521-412c-bd2a-97b6d8829b5f.png)

2021-10-13 09:58 UTC, srindom commented
@zakariaelas would it be possible to get filter them when calling `fetchCartOptions` - something like:
```
const profileIds = productsInCart.map(({ profile_id }) => profile_id)
const optionsToReturn = allOptions.filter(o => profileIds.includes(o.profile_id ))
`

2021-10-15 18:01 UTC, merged