docs: updated file-service s3 guide
medusajs/medusa pull request #4921
Opened 2023-08-31 10:18 UTC by habibullahturkmen

Added description for `download_file_duration` option and recently added `cache_control` option.

2023-08-31 10:40 UTC, shahednasser requested changes
Thank you for your contribution @habibullahturkmen  ! Just a minor fix and it should be good

2023-08-31 10:40 UTC, shahednasser commented on www/docs/content/plugins/file-service/s3.mdx
> +7. `<YOUR_DOWNLOAD_FILE_DURATION_AMOUNT>` is the expiry duration for a download url. For example: expires in 1 hour, `3600`
```suggestion
7. `<YOUR_DOWNLOAD_FILE_DURATION_AMOUNT>` is the expiry duration for a download URL. For example, you can set the value to ``3600`` if you want the download URL to expire in 1 hour.
```

2023-08-31 12:50 UTC, habibullahturkmen commented
> Thank you for your contribution @habibullahturkmen ! Just a minor fix and it should be good

Thank you so much for your feedback, I've applied your feedback.

2023-08-31 13:08 UTC, shahednasser approved these changes
LGTM! Thanks for your contribution!

2023-08-31 13:45 UTC, shahednasser reviewed
Can you run `yarn lint:content --fix` and commit the changes?

2023-08-31 21:33 UTC, habibullahturkmen commented
> Can you run `yarn lint:content --fix` and commit the changes?

I've fixed the lint issue manually.

2023-08-31 21:57 UTC, habibullahturkmen commented
> Can you run `yarn lint:content --fix` and commit the changes?

Done, thank you for your feedback.

2023-09-03 06:59 UTC, habibullahturkmen commented
> Can you run `yarn lint:content --fix` and commit the changes?

I ran yarn lint:content --fix and pushed the code, could you please approve it. Thank you.

2023-09-04 07:54 UTC, merged