feat: 🌐 Add Arabic translations
medusajs/medusa pull request #5140
Opened 2023-09-19 10:23 UTC by PeterAbdalla

2023-09-22 10:58 UTC, shahednasser requested changes
Thank you for your contribution! I think the translation is much better than last time. I left some suggestions for fixes.

Can you also run the command `yarn changeset` in the root of the monorepository, choose the `admin-ui` package, and set the message to the title of this PR?

2023-09-22 10:58 UTC, shahednasser commented on packages/admin-ui/ui/public/locales/ar/translation.json
> +  "activity-drawer-no-notifications-title": "هادئ هنا...",
```suggestion
  "activity-drawer-no-notifications-title": "هدوء هنا...",
```

2023-09-22 10:58 UTC, shahednasser commented on packages/admin-ui/ui/public/locales/ar/translation.json
> +  "analytics-preferences-error": "خطأ",
```suggestion
  "analytics-preferences-error": "حدث خطأ",
```

I think it makes sense to use this translation for all "Error" translations

2023-09-22 10:58 UTC, shahednasser commented on packages/admin-ui/ui/public/locales/ar/translation.json
> +  "analytics-preferences-documentation": "الوثائق",
```suggestion
  "analytics-preferences-documentation": "وثائقنا",
```

2023-09-22 10:58 UTC, shahednasser commented on packages/admin-ui/ui/public/locales/ar/translation.json
> +  "organisms-yes-remove": "نعم، إزالة",
```suggestion
  "organisms-yes-remove": "نعم، إحذف",
```

2023-09-22 10:58 UTC, shahednasser commented on packages/admin-ui/ui/public/locales/ar/translation.json
> +  "error-boundary-400": "كان طلب غير صحيح، قم بإصلاح طلبك ثم حاول مرة أخرى.",
```suggestion
  "error-boundary-400": "الطلب غير صحيح، قم بإصلاح طلبك ثم حاول مرة أخرى.",
```

2023-09-22 10:58 UTC, shahednasser commented on packages/admin-ui/ui/public/locales/ar/translation.json
> +  "error-boundary-404": "لم يتم العثور على الصفحة التي طلبتها ، يرجى التحقق من عنوان URL وحاول مرة أخرى.",
```suggestion
  "error-boundary-404": "لم يتم العثور على الصفحة التي طلبتها ، يرجى التحقق من عنوان الصفحة والمحاولة مرة أخرى.",
```

2023-09-22 10:58 UTC, shahednasser commented on packages/admin-ui/ui/public/locales/ar/translation.json
> +  "help-dialog-we-usually-respond-in-a-few-hours": "عادةً ما نرد خلال بضع ساعات",
```suggestion
  "help-dialog-we-usually-respond-in-a-few-hours": "عادةً نرد خلال بضع ساعات",
```

2023-09-22 10:58 UTC, shahednasser commented on packages/admin-ui/ui/public/locales/ar/translation.json
> +  "help-dialog-what-is-it-about": "ماذا يدور حوله؟...",
```suggestion
  "help-dialog-what-is-it-about": "عن ماذا الموضوع؟...",
```

2023-09-22 10:58 UTC, shahednasser commented on packages/admin-ui/ui/public/locales/ar/translation.json
> +  "invite-modal-invite-users": "دعوة مستخدمين",
```suggestion
  "invite-modal-invite-users": "إدعو مستخدمين",
```

2023-09-22 10:58 UTC, shahednasser commented on packages/admin-ui/ui/public/locales/ar/translation.json
> +  "product-attributes-section-configure-to-calculate-the-most-accurate-shipping-rates": "قم بالتهيئة لحساب أكثر معدلات الشحن دقة",
```suggestion
  "product-attributes-section-configure-to-calculate-the-most-accurate-shipping-rates": "قم بالتهيئة لحساب معدلات الشحن بأكثر دقة",
```

2023-09-22 10:58 UTC, shahednasser commented on packages/admin-ui/ui/public/locales/ar/translation.json
> +  "collection-modal-slug-description": "عنوان URL للمجموعة. سيتم إنشاؤه تلقائيًا إذا ترك فارغًا.",
```suggestion
  "collection-modal-slug-description": "عنوان الصفحة للمجموعة. سيتم إنشاؤه تلقائيًا إذا ترك فارغًا.",
```

2023-09-25 06:56 UTC, shahednasser approved these changes
LGTM!

@olivermrbl would you like to sign off on this as well?

2023-09-27 20:46 UTC, merged

2023-09-29 16:55 UTC, olivermrbl commented
@shahednasser, any specific reason this introduces a major bump? I think we are fine with a patch no?

2023-09-29 17:01 UTC, shahednasser commented
no reason, I think I just missed that 😅