feat(admin-ui): Add Russian translation
medusajs/medusa pull request #5142
Opened 2023-09-19 12:55 UTC by yersultanur

2023-10-15 11:15 UTC, bytadaniel commented
Hello! I really need this localization for my production project. @olivermrbl Could you, please, tell me, in what time frame do you plan to put together a release with Russian localization?

2023-10-15 16:04 UTC, yersultanur commented
@bytadaniel please, if you have time check translation, are you satisfied with it?

2023-10-16 14:49 UTC, bytadaniel commented
@yersultanur Hello! Could you please contact me and help me to startup medusa with your russian i18n. I will be glad to check out the translation. I am a russian native speaker

2023-10-16 17:51 UTC, yersultanur commented
@bytadaniel t.me/mirvoinaput you contact me through telegram, and I will send you json, so you can take a look on translation

2023-10-26 09:30 UTC, VariableVic requested changes

2023-10-26 09:30 UTC, VariableVic commented on packages/admin-ui/ui/src/i18n/index.ts
> +const adminPath = process.env.ADMIN_PATH ? `${process.env.ADMIN_PATH}` : "/"
This part is outdated, could you resolve the conflicts please? Then we can merge the translation.

2023-10-26 15:08 UTC, yersultanur commented
@VariableVic Hi ,is it good now?

2023-10-26 15:45 UTC, VariableVic approved these changes
Looks good now, thanks! Nice work

2023-10-30 14:12 UTC, merged