Feat/soft delete pricing entities
medusajs/medusa pull request #5858
Opened 2023-12-13 12:20 UTC by pKorsholm

2023-12-15 09:21 UTC, adrien2p requested changes

2023-12-15 09:21 UTC, adrien2p commented on packages/pricing/src/services/pricing-module.ts
> +  }
todo: can you look at the product module and match the impl, it will facilitate future things ahah :)

2023-12-15 09:21 UTC, adrien2p commented on packages/types/src/pricing/common/price-rule.ts
> +  updated_at?: null | Date
question: those two are always present and with a default value no? This DTO is that one that reflect what is returned by the module by default right?

2023-12-15 09:21 UTC, adrien2p commented on packages/types/src/pricing/common/price-set-money-amount.ts
> +   * When the price_set_money_amount was deleted.
same question

2023-12-15 09:21 UTC, adrien2p commented on packages/types/src/pricing/service.ts
> +   * } from "@medusajs/pricing"
comment: At some point we will have to start using the medusa app like:
```ts
const { modules } = await MedusaApp({
    modulesConfig,
    servicesConfig: joinerConfig,
    injectedDependencies,
  })
```

not now but just to say

2023-12-15 10:27 UTC, riqwan approved these changes
lgtm, this is missing the linkable keys concept, but can also be done as a separate ticket.

2024-01-02 10:08 UTC, olivermrbl commented
@adrien2p can I get you to give this another review?

2024-01-02 10:19 UTC, adrien2p approved these changes
LGTM, few todo's but nothing major :)

2024-01-02 10:19 UTC, adrien2p commented on packages/pricing/src/models/price-rule.ts
> +  deleted_at: Date
todo: `| null`

2024-01-02 10:19 UTC, adrien2p commented on packages/pricing/src/models/price-set-money-amount.ts
>    price_list?: PriceList
todo: `| null`

2024-01-02 10:19 UTC, adrien2p commented on packages/pricing/src/models/price-set-money-amount.ts
> +  deleted_at: Date
todo: `| null`

2024-01-02 10:19 UTC, adrien2p commented on packages/pricing/src/models/price-set-money-amount.ts
>    onCreate() {
todo:  we are missing the onInit for the id generation

2024-01-04 08:02 UTC, olivermrbl commented
> this is missing the linkable keys concept, but can also be done as a separate ticket.

What are next steps for this one?

2024-01-04 08:02 UTC, merged