Add admin API fixture for Shipping Profile
medusajs/medusa pull request #699
Opened 2021-10-31 13:03 UTC by l4u

#476

2021-11-03 14:35 UTC, olivermrbl requested changes
All good! Just a single `console.log` we need to get rid off :)

2021-11-03 14:35 UTC, olivermrbl commented on integration-tests/docs/test-input/admin/shipping-profile.js
> +    console.log(newProfile)
Remove

2021-11-06 03:14 UTC, l4u commented
removed the extra `console.log`

2021-11-07 18:13 UTC, olivermrbl approved these changes
Many thanks for the contribution ❤️

2021-11-07 18:13 UTC, merged