Feat/tax
medusajs/medusa pull request #7026
Opened 2024-04-09 10:37 UTC by riqwan

2024-04-09 14:17 UTC, kasperkristensen requested changes
There are quite a few missing translations, I've tried to mark as many as possible but properly a few I didn't catch. The same for eslint and TS errors/warnings. 

Also would be awesome if you could try to conform to the file structure we use throughout the project, so we keep everything aligned across the project 👍

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/hooks/table/columns-v2/use-tax-rates-table-columns.tsx
> +import { createColumnHelper } from "@tanstack/react-table"
move to normal columns folder

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-region-detail/tax-region-detail.tsx
> +      <div className="flex flex-col gap-y-6">
Too much spacing need to be gap-y-2 like the rest of admin

```suggestion
      <div className="flex flex-col gap-y-2">
```

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-region-list/components/region-list-table/tax-region-list-table.tsx
> +
use `asChild` so the button styles are used for the focus state rather than the Link built in style.

```suggestion
          <Button size="small" variant="secondary" asChild>
              <Link to="/settings/taxes/create">
                  {t("actions.create")}
              </Link>
          </Button>
      </div>
```

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-region-list/components/region-list-table/tax-region-list-table.tsx
>          navigateTo={(row) => `${row.original.id}`}
q: if filters, orderBy, and search are not supported by the API then we should create a ticket for it in Linear as this needs to be supported for every list endpoint

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-province-create/components/tax-region-create-form.tsx
> +import { zodResolver } from "@hookform/resolvers/zod"
instead of having it in /components it should be /components/tax-region-create-form/tax-region-create-form. But since this component is used in multiple pages, it would be better to move it to /taxes/common/components/tax-region-create-form

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-province-create/components/tax-region-create-form.tsx
> +          <div className="flex flex-col gap-y-8 min-w-[400px]">
Needs to be aligned with styling of FocusModal in the rest of admin

```suggestion
          <div className="flex flex-col gap-y-8 w-full max-w-[720px]">
```

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-province-create/components/tax-region-create-form.tsx
> +                      <Form.Label>Is combinable?</Form.Label>
needs translation, and this could properly also use a hint to explain what it does.

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-create/components/condition.tsx
> +          Tax Rate applies to
needs to be translated

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-province-create/components/tax-region-create-form.tsx
> +            {!taxRegion && (
Think we should do a two grid column layout for screens larger than md, and 1 columns for small screens. Would also be nice to separate the fields that are related to the tax rate, and the ones that are the default tax rate:

Title
Subtitle

[ country ]

____________________________

Default tax rate
Some hint about what this is.

Name label            Rate label
[        Name       ]   [       Rate          ] 

Code label
[        Code         ]

Is combinable?                                  [ Switch ]
Hint about what this means

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-region-detail/tax-region-detail.tsx
> +        <Outlet />
Missing JSON view

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-region-detail/components/tax-rate-list.tsx
> +  }
```suggestion
    await mutateAsync(undefined, {
      onSuccess: () => {
        setRowSelection({})
      },
    })
  }
```

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-region-detail/components/tax-rate-list.tsx
> +      }),
translation key is wrong

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-region-detail/tax-region-detail.tsx
> +}
remove

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-region-list/components/region-list-table/tax-region-list-table.tsx
>    const filters = useRegionTableFilters()
This isn't getting passed to the table

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-province-create/components/tax-region-create-form.tsx
> +      }
Anonymous arrow functions are not allowed by our eslint config, so lets change this to follow our rules

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-create/components/condition.tsx
> +}
nit: move to a separate file, in order for React Fast Refresh to work properly component files should only export components.

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-create/components/condition.tsx
> +  type,
unused prop

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-create/components/condition.tsx
> +  const isExButtonDisabled = !!labels.length && isInOperator
not used

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-create/components/tax-rate-create-form.tsx
> +  const { mutateAsync } = useCreateTaxRate()
use isPending from here for the loading state

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-create/components/tax-rate-create-form.tsx
> +  const [isLoading, setIsLoading] = useState(false)
rm

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-create/components/tax-rate-create-form.tsx
> +  const selectedTypes = Object.keys(selectedConditionTypes)
selectedConditionTypes might be undefined here, need to either check for it or do || {}

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-create/components/tax-rate-create-form.tsx
> +                      Creates a tax rate overrides for a tax region
missing translation

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-create/components/tax-rate-create-form.tsx
> +                          </Form.Item>
need to destructure fields, and make sure not to pass value to <Switch value /> which is currently happening. The same for onChange as the handler should only be set onCheckedChange, its currently being set on both.

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-edit/components/tax-rate-edit-form.tsx
> +  const { mutateAsync } = useUpdateTaxRate(taxRate.id)
use isPending for loading state

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-edit/components/tax-rate-edit-form.tsx
> +  const [isLoading, setIsLoading] = useState(false)
remove

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-edit/components/tax-rate-edit-form.tsx
> +                      Edits tax rate for a tax region
missing translation

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-edit/components/tax-rate-edit-form.tsx
> +                <div className="flex flex-col gap-y-8 md:min-w-[400px]">
follow general style for FocusModal here as well: w-full max-w-[720px]

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-edit/components/tax-rate-edit-form.tsx
> +                            <Form.Label>Is combinable?</Form.Label>
translation + hint here

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-edit/components/tax-rate-edit-form.tsx
> +                              />
destructure field and make sure that value and onChange is only passed to the proper fields.

2024-04-09 14:17 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-rate-edit/components/tax-rate-edit-form.tsx
> +              />
ts complains here

2024-04-09 14:24 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-region-detail/components/tax-region-general-detail.tsx
> +            Manage your region's tax structure
missing translation

2024-04-09 14:24 UTC, kasperkristensen commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-region-detail/components/tax-region-general-detail.tsx
> +        <Text size="small" leading="compact" className="text-right">
shouldn't be `text-right`

2024-04-15 09:07 UTC, riqwan commented on packages/admin-next/dashboard/src/v2-routes/taxes/tax-province-create/components/tax-region-create-form.tsx
> +            {!taxRegion && (
Is the grid for the modal, form or the fields?

2024-04-16 07:56 UTC, kasperkristensen approved these changes
LGTM

2024-04-16 08:26 UTC, merged