Code Issue in /plugins/notifications/sendgrid #7068
medusajs/medusa pull request #7115
Opened 2024-04-22 07:02 UTC by tesfamickal

changed order_shipped_template to be renamed to order_shipment_created_template

2024-05-31 21:59 UTC, MohmDev commented
> changed order_shipped_template to be renamed to order_shipment_created_template

Yes I found this issue too. Took me a day to figure this out.

2024-06-03 07:24 UTC, shahednasser requested changes
@tesfamickal can I get you to rebase to the `v1.x` branch?

2024-06-03 07:24 UTC, shahednasser commented on www/apps/docs/content/plugins/notifications/sendgrid.mdx
> +**Key in plugin options:** `order_shipment_created_template`
```suggestion
**Key in plugin options:** `order_shipment_created_template` in the root options, and `order_shipped_template` in the localization options.
```

2024-06-05 16:48 UTC, tesfamickal commented on www/apps/docs/content/plugins/notifications/sendgrid.mdx
> +**Key in plugin options:** `order_shipment_created_template`
@shahednasser sure thing

2024-07-05 13:07 UTC, riqwan commented
Hey, thanks for the PR! Since v2 brought a lot of architectural changes, we will be closing this PR since it no longer applies to our new setup.

If you would still like to open this PR, please rebase with the v1 branch and re-request a review & we'll get back on it quickly.

2024-07-05 13:07 UTC, closed without merging