Feat: Convert admin/collections to typescript
medusajs/medusa pull request #782
Opened 2021-11-12 08:58 UTC by pKorsholm

2021-11-12 11:46 UTC, srindom requested changes

2021-11-12 11:46 UTC, srindom commented on packages/medusa/src/api/routes/admin/collections/index.ts
> +export type AdminCollectionResponse = {
```suggestion
export type AdminCollectionsRes = {
```

2021-11-12 11:46 UTC, srindom commented on packages/medusa/src/api/routes/admin/collections/list-collections.ts
> +export class AdminGetCollectionsReq {
```suggestion
export class AdminGetCollectionsParams {
```

2021-11-12 11:46 UTC, srindom commented on packages/medusa/src/api/routes/admin/collections/index.ts
> +export type AdminListCollectionsResponse = {
```suggestion
export type AdminCollectionsListRes = {
```

2021-11-16 12:47 UTC, olivermrbl requested changes

2021-11-16 12:47 UTC, olivermrbl commented on packages/medusa/src/api/routes/admin/collections/index.ts
> +export type AdminCollectionsListRes = {
Use `PaginatedResponse` :)

2021-11-16 12:47 UTC, olivermrbl commented on packages/medusa/src/api/routes/admin/collections/list-collections.ts
> +  offset?: number
These need `@Type(() => Number)` decorator
```suggestion
  @IsNumber()
  @IsOptional()
  @Type(() => Number)
  limit?: number

  @IsNumber()
  @IsOptional()
  @Type(() => Number)
  offset?: number
```

2021-11-16 15:13 UTC, olivermrbl approved these changes
LGTM

2021-11-16 15:14 UTC, merged