feat: typed admin/return-reasons
medusajs/medusa pull request #784
Opened 2021-11-12 09:45 UTC by kasperkristensen

2021-11-12 11:43 UTC, srindom requested changes

2021-11-12 11:43 UTC, srindom commented on packages/medusa/src/api/routes/admin/return-reasons/index.ts
> +export type AdminReturnReasonsResponse = {
```suggestion
export type AdminReturnReasonsRes = {
```

2021-11-12 11:43 UTC, srindom commented on packages/medusa/src/api/routes/admin/return-reasons/list-reasons.ts
> +}
Move to index - `AdminReturnReasonsListRes`

2021-11-15 07:24 UTC, pKorsholm commented on packages/medusa/src/api/routes/admin/return-reasons/create-reason.ts
>   *     application/json:
remember to include the required fields(vaule, label) in the OAS documentation schema as 
```
schema: 
  required: 
    - value
    - label
```

2021-11-15 11:00 UTC, olivermrbl approved these changes
LGTM

2021-11-16 13:32 UTC, merged