feat: typed admin/shipping-profiles
medusajs/medusa pull request #786
Opened 2021-11-12 10:44 UTC by kasperkristensen

2021-11-12 11:40 UTC, srindom approved these changes

2021-11-12 12:22 UTC, olivermrbl requested changes

2021-11-12 12:22 UTC, olivermrbl commented on packages/medusa/src/api/routes/admin/shipping-profiles/index.ts
> +export type AdminShippingProfilesRes = {
Should be:
```suggestion
export type AdminShippingProfilesListRes = {
```

2021-11-15 10:56 UTC, olivermrbl approved these changes

2021-11-15 11:04 UTC, merged