Typescript admin customers
medusajs/medusa pull request #790
Opened 2021-11-12 12:45 UTC by pKorsholm

2021-11-12 14:55 UTC, srindom requested changes

2021-11-12 14:55 UTC, srindom commented on packages/medusa/src/api/routes/admin/customers/list-customers.ts
> +}
Should probably be moved to `types/customers.ts` so it can be used in `CustomerService.list`

2021-11-16 14:04 UTC, olivermrbl requested changes
Minor fixes, and then a rebase of from `develop` to remove the permissions tests :)

2021-11-16 14:04 UTC, olivermrbl commented on packages/medusa/src/api/routes/admin/customers/list-customers.ts
> +  offset?: number
```suggestion
  @IsNumber()
  @Type(() => Number)
  @IsOptional()
  limit?: number

  @IsNumber()
  @Type(() => Number)
  @IsOptional()
  offset?: number
```

2021-11-16 14:04 UTC, olivermrbl commented on packages/medusa/src/api/routes/admin/customers/index.ts
> +export type AdminCustomerRes = {
nit:
```suggestion
export type AdminCustomersRes = {
```

2021-11-16 14:54 UTC, olivermrbl commented
Please remove `package-lock.json` from `packages/medusa` @pKorsholm ;)

2021-11-16 15:55 UTC, pKorsholm commented
done, thought i didn't push those 😅

2021-11-17 07:24 UTC, olivermrbl requested changes

2021-11-17 07:57 UTC, olivermrbl approved these changes

2021-11-17 07:58 UTC, merged