docs: update to include Supabase S3 File Provider
medusajs/medusa pull request #8715
Opened 2024-08-22 02:03 UTC by 420coupe

update to include instructions for Supabase S3 Storage

2024-08-22 12:12 UTC, shahednasser requested changes
Hi @420coupe thank you for this contribution!

I tried following along the steps but it seems like there's a compatibility issue between the S3 file provider and supabase's storage. Did you get it working? If so, can you share what your configurations look like (without secrets, just want to make sure that the configurations I used were correct).

I also added comments for changes text-wise.

2024-08-22 12:12 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +    <TabsTrigger value="suapbase">Supabase S3 Storage</TabsTrigger>
```suggestion
    <TabsTrigger value="supabase">Supabase S3 Storage</TabsTrigger>
```

2024-08-22 12:12 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +<TabsContent value="supabase">
```suggestion
    <TabsContent value="supabase">
```

2024-08-22 12:12 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +    - [Supabase account](https://supabase.com/dashboard/sign-in?returnTo=%2Fprojects).
```suggestion
    - [Supabase account](https://supabase.com/dashboard/sign-in) with a project.
```

2024-08-22 12:12 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +    - Create [New Project]
```suggestion
```

2024-08-22 12:12 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +      1. On your bucket's dashboard, under configuration, click polocies.
```suggestion
      1. On your bucket's dashboard, click on Policies under the Configuration sidebar.
```

2024-08-22 12:12 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +      2. Click on New Policy under Other policies under storage.objects.
```suggestion
      2. Click on New Policy under "Other policies under storage.objects".
```

2024-08-22 12:12 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +      3. Click get started quickly and enable insert access for authenticated users only.
```suggestion
      3. Click get started quickly, choose "insert access for authenticated users only", and click the "Use this template" button.
```

2024-08-22 12:12 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +      4. Click ALL instead of INSERT, then review and save policy.
```suggestion
      4. Click ALL for "Allowed Operations", click the "Review" button, then the "Save policy" button.
```

2024-08-22 12:12 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +      9. Copy settings for ``S3_ENDPOINT``, ``S3_REGION``, ``S3_BUCKET``, ``S3_ACCESS_KEY``, ``S3_SECRET_KEY``
```suggestion
```

No need for these as you already added the link to the S3 access key guide above.

2024-08-22 12:12 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +      - For Supabase, it's the Endpoint url
```suggestion
      - For Supabase, it's the Endpoint URL in the [Storage Settings](https://supabase.com/docs/guides/storage/s3/authentication?queryGroups=language&language=javascript#s3-access-keys).
```

2024-08-22 12:12 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +      - for Supabase, it's `https://{uniqueID}.supabase.co/storage/v1/object/public/{bucket}`.
```suggestion
      - for Supabase, it's `https://{uniqueID}.supabase.co/storage/v1/object/public/{bucket}`. You can retrieve the `uniqueID` from [Storage Settings](https://supabase.com/docs/guides/storage/s3/authentication?queryGroups=language&language=javascript#s3-access-keys) page in the Endpoint URL.
```

2024-08-22 16:29 UTC, 420coupe commented
> Hi @420coupe thank you for this contribution!
> 
> I tried following along the steps but it seems like there's a compatibility issue between the S3 file provider and supabase's storage. Did you get it working? If so, can you share what your configurations look like (without secrets, just want to make sure that the configurations I used were correct).
> 
> I also added comments for changes text-wise.

Yes, was able to get this working. 

#medusa-config.js

```js
[Modules.FILE]: {
      resolve: "@medusajs/file",
      options: {
        providers: [
          {
            resolve: "@medusajs/file-s3",
            id: "s3",
            options: {
              file_url: process.env.SUPABASE_S3_FILE_URL,
              access_key_id: process.env.SUPABASE_S3_ACCESS_KEY,
              secret_access_key: process.env.SUPABASE_S3_SECRET_KEY,
              region: process.env.SUPABASE_S3_REGION,
              bucket: process.env.SUPABASE_S3_BUCKET,
              endpoint: process.env.SUPABASE_S3_ENDPOINT,
              additional_client_config: {
                forcePathStyle: true,
              },
            },
          },
        ],
      },
    },
```
    
#.env
  



  ```js
  SUPABASE_S3_FILE_URL=https://{uniqueIdFromEndpointUrl}.supabase.co/storage/v1/object/public/{bucketName}
SUPABASE_S3_ACCESS_KEY={accessKey}
SUPABASE_S3_SECRET_KEY={secretKey}
SUPABASE_S3_ENDPOINT={endpointUrl}
SUPABASE_S3_REGION={region}
SUPABASE_S3_BUCKET=[bucketName}
```

2024-08-23 07:40 UTC, shahednasser requested changes
Adding `forcePathStyle` fixed it, and someone else reported something similar for minio.

Can you add a section before troubleshooting called "Additional Configuration for MinIO and Supabase" mentioning that it's important to add this config for those two storage services (with a code snippet of the option)?

2024-08-23 08:59 UTC, shahednasser requested changes
Thanks for the change! But I meant to add the following before `## Troubleshooting`:

~~~

## Additional Configuration for MinIO and Supabase

If you're using MinIO or Supabase, set `forcePathStyle` to `true` in the `additional_client_config` object.

For example:

```js title="medusa-config.js"
module.exports = defineConfig({
  // ...
  modules: {
    [Modules.FILE]: {
      resolve: "@medusajs/file",
      options: {
        providers: [
          {
            resolve: "@medusajs/file-s3",
            id: "s3",
            options: {
              // ...
              additional_client_config: {
                forcePathStyle: true,
              },
            },
          },
        ],
      },
    },
  }
})
```

---

~~~

And then remove the new troubleshooting file you added.

2024-08-23 09:07 UTC, 420coupe commented
> Thanks for the change! But I meant to add the following before `## Troubleshooting`:
> 
> ```
> 
> ## Additional Configuration for MinIO and Supabase
> 
> If you're using MinIO or Supabase, set `forcePathStyle` to `true` in the `additional_client_config` object.
> 
> For example:
> 
> ```js title="medusa-config.js"
> module.exports = defineConfig({
>   // ...
>   modules: {
>     [Modules.FILE]: {
>       resolve: "@medusajs/file",
>       options: {
>         providers: [
>           {
>             resolve: "@medusajs/file-s3",
>             id: "s3",
>             options: {
>               // ...
>               additional_client_config: {
>                 forcePathStyle: true,
>               },
>             },
>           },
>         ],
>       },
>     },
>   }
> })
> ```
> 
> ---
> ```
> 
> And then remove the new troubleshooting file you added.

think i got it now.. maybe

2024-08-23 10:20 UTC, shahednasser approved these changes
One last change and we're ready to go 😄 I'll commit the suggestion

2024-08-23 10:20 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/file/s3/page.mdx
> +```
~~~suggestion
```
---

~~~

2024-08-23 10:21 UTC, shahednasser commented
Thank you for your contribution @420coupe !

2024-08-23 11:10 UTC, merged