feat(notification-sendgrid): include ability to handle attachments
medusajs/medusa pull request #8729
Opened 2024-08-22 16:11 UTC by 420coupe

feat(notification-sendgrid): include ability to handle attachments array if passed to dynamicTemplateData.attachments

attachments array objects must contain the following: 

```ts
interface Attachment {
  content: string
  filename: string
  type?: string
  disposition?: string
  content_id?: string
}```

2024-08-24 17:14 UTC, carlos-r-l-rodrigues approved these changes
LGTM

@sradevski can you review this one?

2024-08-25 15:18 UTC, 420coupe commented
updated docs to include attachments example.

2024-08-26 01:59 UTC, 420coupe commented
Another update, include ability to change ``from`` email. From email must be verified as a single sender.

2024-08-26 07:00 UTC, sradevski reviewed
Looks pretty good, just some minor comments 👍

2024-08-26 07:00 UTC, sradevski commented on packages/modules/providers/notification-sendgrid/src/services/sendgrid.ts
> +  type?: string
Let's call it `content_type` so it's clearer what it is. That should also remove the need for a comment in the code.

2024-08-26 07:00 UTC, sradevski commented on packages/modules/providers/notification-sendgrid/src/services/sendgrid.ts
> +  content_id?: string
This one can be called `id`, as it is the attachment ID essentially.

2024-08-26 07:00 UTC, sradevski commented on packages/modules/providers/notification-sendgrid/src/services/sendgrid.ts
> +        ? data.from
I am thinking we might want to add `from` as part of the `NotificationDTO` model (but optional). I can see it being useful in other channels as well, so it's better if it is a first-class citizen.

2024-08-26 07:08 UTC, 420coupe commented on packages/modules/providers/notification-sendgrid/src/services/sendgrid.ts
> +  content_id?: string
content_id is the required var name from sendgrid

https://www.twilio.com/docs/sendgrid/api-reference/mail-send/mail-send#request-body

2024-08-26 07:09 UTC, 420coupe commented on packages/modules/providers/notification-sendgrid/src/services/sendgrid.ts
> +  type?: string
calling sendgrid defined variables. 

https://www.twilio.com/docs/sendgrid/api-reference/mail-send/mail-send#request-body

2024-08-26 07:09 UTC, 420coupe commented on packages/modules/providers/notification-sendgrid/src/services/sendgrid.ts
> +        ? data.from
This was my thought, but i didnt want to add a breaking change. If we're moving towards making it a first-class i'll drop this piece.

2024-08-26 08:24 UTC, sradevski commented on packages/modules/providers/notification-sendgrid/src/services/sendgrid.ts
> +        ? data.from
It's not a breaking change since it will be optional, so let's go for it 👍

2024-08-26 08:25 UTC, sradevski commented on packages/modules/providers/notification-sendgrid/src/services/sendgrid.ts
> +  content_id?: string
I was only thinking we can name it `id` internally, and remap it to `content_id`, but it's a NIT one.

2024-08-26 08:26 UTC, sradevski commented on packages/modules/providers/notification-sendgrid/src/services/sendgrid.ts
> +  type?: string
Same logic as below, as I am thinking we can reuse the attachment type for other providers as well, so we can name it as we think makes sense, and remap it in each provider.

2024-08-26 16:03 UTC, 420coupe commented
@sradevski ok made em as optional first-class vars.

2024-08-27 08:42 UTC, sradevski approved these changes

2024-08-27 13:20 UTC, sradevski approved these changes

2024-08-27 13:43 UTC, shahednasser requested changes

2024-08-27 13:43 UTC, shahednasser commented on www/apps/resources/app/architectural-modules/notification/sendgrid/page.mdx
> +- The `from` optional property allows you to pass a single sender verified email, default is `SENDGRID_FROM` env variable.
```suggestion
- The `from` optional property allows you to pass a single sender-verified email. If not provided, the value of the `from` configuration of the module is used.
```

2024-08-28 06:39 UTC, shahednasser approved these changes
LGTM

2024-08-28 06:39 UTC, merged