Fix: Correct module path and clarify config structure in Medusa v2 Docs
medusajs/medusa pull request #9222
Opened 2024-09-21 16:25 UTC by aqeebpathan

### What
This PR addresses an issue in the Medusa v2 documentation regarding the module creation example. The import paths were corrected to reflect the proper directory structure, ensuring clarity for users.

Closes #9220 

### Why
The previous documentation contained incorrect import paths that could lead to confusion for users attempting to create and configure modules. Clarifying the structure aims to prevent similar issues for future users.

### How
- Updated the import statements in the documentation to go two levels up instead of three.
- Added clarification in the `medusa-config.js` example to indicate that the `modules` node should be a part of `projectConfig`.

### Testing
While documentation changes do not require formal testing, I reviewed the updated paths and descriptions against the current code structure to ensure accuracy and clarity.

### Note
This is my first contribution to an open source project, and I'm excited to contribute to the Medusa community!

2024-09-21 22:12 UTC, damien-thiesson approved these changes
LGTM

2024-09-21 22:18 UTC, olivermrbl commented
Thanks for the contribution. Will let @shahednasser take a look at it!

2024-09-23 06:47 UTC, shahednasser requested changes
Thanks for your contribution, just need a small change.

2024-09-23 06:47 UTC, shahednasser commented on www/apps/book/app/basics/modules-and-services/page.mdx
>  ```js title="medusa-config.js" highlights={[["4", "helloModuleService", "The key of the main service to be registered in the Medusa container."]]}
```suggestion
```js title="medusa-config.js" highlights={[["7", "helloModuleService", "The key of the main service to be registered in the Medusa container."]]}
```

2024-09-23 13:33 UTC, shahednasser approved these changes
LGTM thanks!

2024-09-23 13:55 UTC, merged