fix(#936): updates discord links.
medusajs/medusa pull request #937
Opened 2021-12-15 21:51 UTC by roman-bytes

This should close #936

2021-12-16 08:41 UTC, srindom requested changes
Please omit the `yarn.lock` from this PR :)

2021-12-20 07:48 UTC, olivermrbl approved these changes
LGTM, thanks! 👍

2022-01-04 11:41 UTC, avneesh0612 approved these changes

2022-01-04 15:06 UTC, srindom commented
Actually! We got ourselves a vanity link so can we change it to https://discord.gg/medusajs :)

2022-02-09 18:39 UTC, srindom approved these changes

2022-02-09 18:39 UTC, merged