Update page.mdx
medusajs/medusa pull request #9478
Opened 2024-10-04 15:46 UTC by erickirt

this link leads no where and if spelling is corrected, still leads no where: https://docs.medusajs.com/resources/medusa-container-resources

2024-10-04 15:47 UTC, erickirt commented
Do not merge this, i did not add a fix, just a commented complaint

2024-10-06 22:25 UTC, damien-thiesson commented
> Do not merge this, i did not add a fix, just a commented complaint

Hi @erickirt, thank you for your report and contribution. Pull requests are used to fix the source code, rather than just reporting an issue. To report an issue with the documentation without fixing the code yourself, you can click on [Report issue](https://github.com/medusajs/medusa/issues/new?assignees=&labels=type%3A+docs&template=docs.yml&title=Medusa%20v2%20Docs%3A%20Issue%20in%201.%20Introduction%20-%20Medusa%20v2%20Docs) in the top right corner of any documentation page. This will create a [Github issue](https://github.com/medusajs/medusa/issues) that can then be picked up by someone to push an actual PR to fix the link.

Can you close this PR and create an issue instead?

Many thanks :)

2024-10-06 22:27 UTC, damien-thiesson requested changes
Requesting to close this PR and create an issue instead.

2024-10-07 07:02 UTC, shahednasser requested changes

2024-10-07 07:02 UTC, shahednasser commented on www/apps/book/app/advanced-development/modules/container/page.mdx
> +Find a list of resources or dependencies registered in a module's container in [this Learning Resources reference](!resoures!/medusa-container-resources). <_THIS LEADS NO WHERE
Nice catch, can you please change it to this:

```suggestion
Find a list of resources or dependencies registered in a module's container in [this Learning Resources reference](!resources!/medusa-container-resources).
```

2024-10-07 07:02 UTC, shahednasser commented on www/apps/book/app/advanced-development/modules/container/page.mdx
>  ---
Please don't remove this.

2024-11-13 01:58 UTC, closed without merging