Added cookieMaxAge in Config
medusajs/medusa pull request #948
Opened 2021-12-19 19:29 UTC by NiketanG

Adds a custom cookieMaxAge in Medusa Config that will be used to set a custom cookie expiry time. Uses the default settings if no config value is provided.

#947

2021-12-26 23:57 UTC, timtamimi commented on packages/medusa/src/config/index.js
> +  // Max Age for Session Cookie. 10 Hours by default
My only nit-pick would be to consider changing the comment to use the same format as the other comments, just to keep the convention.

E.g. 
```
/**
* Max Age for Session Cookie. 10 Hours by default
*/
```

2021-12-28 12:27 UTC, srindom requested changes
Good idea! I think it would be nicer if this could be configured from the `medusa-config.js` file. You can use `getConfigFile` from `medusa-core-utils` to retrieve the project config :)

2021-12-28 19:11 UTC, NiketanG commented
> Good idea! I think it would be nicer if this could be configured from the `medusa-config.js` file. You can use `getConfigFile` from `medusa-core-utils` to retrieve the project config :)

Done.

2022-01-03 16:46 UTC, olivermrbl commented
Can I get you to change base branch to `develop` and rebase off of it? 😃 @NiketanG

2022-01-05 07:59 UTC, olivermrbl commented
> Can I get you to change base branch to `develop` and rebase off of it? @NiketanG
> 
> _edit: It also seems, that the changes have gone missing 😄_

Any update on the missing changes here @NiketanG ? 😄

2022-01-06 12:05 UTC, merged