Fix(medusa-js/medusa) Fix type in AdminProductListTagsRest to use tags instead of types
medusajs/medusa pull request #958
Opened 2021-12-31 14:32 UTC by adrien2p

The actual type exposed a property `types` which is more link to the product-types. Instead it should expose a property `tags` otherwise you end up with a type error trying to access tags from the response type

2022-01-02 13:32 UTC, olivermrbl reviewed
Thanks @adrien2p ! Can I get you to change base branch to `develop` and rebase off of it? :)

2022-01-03 10:53 UTC, adrien2p commented
Oups sorry though I did it ^^

2022-01-04 18:37 UTC, olivermrbl requested changes

2022-01-04 18:37 UTC, olivermrbl commented on packages/medusa-js/src/resources/admin/products.ts
> -  AdminPostProductsProductOptionsReq,
These imports should not be deleted :)

2022-01-04 20:57 UTC, adrien2p commented on packages/medusa-js/src/resources/admin/products.ts
> -  AdminPostProductsProductOptionsReq,
My bad wrong manip ;)

2022-01-05 07:17 UTC, olivermrbl approved these changes

2022-01-06 16:45 UTC, merged